// Generated by labelle-engine for project: example_1
// Do not edit manually - regenerate with: zig build generate

const std = @import("std");
const engine = @import("labelle-engine");

const Game = engine.Game;
const ProjectConfig = engine.ProjectConfig;

// Prefabs
const enemy_prefab = @import("prefabs/enemy.zig");
const player_prefab = @import("prefabs/player.zig");

// Components
const velocity_comp = @import("components/velocity.zig");
const gravity_comp = @import("components/gravity.zig");
const health_comp = @import("components/health.zig");

// Component type exports
pub const Velocity = velocity_comp.Velocity;
pub const Gravity = gravity_comp.Gravity;
pub const Health = health_comp.Health;

// Scripts
const gravity_script = @import("scripts/gravity.zig");

// Registries
pub const Prefabs = engine.PrefabRegistry(.{
    enemy_prefab,
    player_prefab,
});

const main_module = @This();

pub const Components = engine.ComponentRegistry(struct {
    pub const Velocity = main_module.Velocity;
    pub const Gravity = main_module.Gravity;
    pub const Health = main_module.Health;
});

pub const Scripts = engine.ScriptRegistry(struct {
    pub const gravity = gravity_script;
});

pub const Loader = engine.SceneLoader(Prefabs, Components, Scripts);
pub const initial_scene = @import("scenes/game_scene.zon");

pub fn main() !void {
    const ci_test = std.posix.getenv("CI_TEST") != null;

    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const project = try ProjectConfig.load(allocator, "project.labelle");
    defer project.deinit(allocator);

    var game = try Game.init(allocator, .{
        .window = .{
            .width = project.window.width,
            .height = project.window.height,
            .title = "labelle Game",
            .target_fps = project.window.target_fps,
            .hidden = ci_test,
        },
        .clear_color = .{ .r = 30, .g = 35, .b = 45 },
    });
    defer game.deinit();

    const ctx = engine.SceneContext.init(&game);
    var scene = try Loader.load(initial_scene, ctx);
    defer scene.deinit();

    if (ci_test) return;

    while (game.isRunning()) {
        const dt = game.getDeltaTime();
        scene.update(dt);
        game.getPipeline().sync(game.getRegistry());

        const re = game.getRetainedEngine();
        re.beginFrame();
        re.render();
        re.endFrame();
    }
}
