// ============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT
// ============================================================================
// This file is generated by labelle-engine from project.labelle
// Project: mobile_physics_test
//
// Any manual changes will be overwritten on next generation.
//
// To regenerate: zig build generate
// To modify settings: edit project.labelle instead
// ============================================================================

const std = @import("std");
const engine = @import("labelle-engine");
const ProjectConfig = engine.ProjectConfig;

pub const GameId = u64;
const bouncing_ball_prefab = @import("prefabs/bouncing_ball.zon");
const physics_sim_script = @import("scripts/physics_sim.zig");
const main_module = @This();
pub const Prefabs = engine.PrefabRegistry(.{
    .bouncing_ball = bouncing_ball_prefab,
});
pub const Components = engine.ComponentRegistry(struct {
    // Engine built-in components
    pub const Position = engine.Position;
    pub const Sprite = engine.Sprite;
    pub const Shape = engine.Shape;
    pub const Text = engine.Text;
    // Physics components (auto-included when physics is enabled)
    pub const RigidBody = engine.PhysicsComponents.RigidBody;
    pub const Collider = engine.PhysicsComponents.Collider;
    pub const Velocity = engine.PhysicsComponents.Velocity;
});
pub const Scripts = engine.ScriptRegistry(struct {
    pub const physics_sim = physics_sim_script;
});
const Game = engine.Game;

pub const Loader = engine.SceneLoader(Prefabs, Components, Scripts);
pub const initial_scene = @import("scenes/main.zon");

pub fn main() !void {
    const ci_test = std.posix.getenv("CI_TEST") != null;

    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const project = try ProjectConfig.load(allocator, "project.labelle");
    defer project.deinit(allocator);

    // Convert title to sentinel-terminated string for window creation
    const title = try allocator.dupeZ(u8, project.window.title);
    defer allocator.free(title);

    var game = try Game.init(allocator, .{
        .window = .{
            .width = project.window.width,
            .height = project.window.height,
            .title = title,
            .target_fps = project.window.target_fps,
            .hidden = ci_test,
        },
        .clear_color = .{ .r = 30, .g = 35, .b = 45 },
    });
    game.fixPointers(); // Fix internal pointers after struct is in final location
    defer game.deinit();

    // Load atlases from project config
    for (project.resources.atlases) |atlas| {
        try game.loadAtlas(atlas.name, atlas.json, atlas.texture);
    }

    // Apply camera configuration from project
    if (project.camera.x != null or project.camera.y != null) {
        game.setCameraPosition(project.camera.x orelse 0, project.camera.y orelse 0);
    }
    if (project.camera.zoom != 1.0) {
        game.setCameraZoom(project.camera.zoom);
    }

    const ctx = engine.SceneContext.init(&game);

    // Emit scene_before_load hook for initial scene (mirrors Game.setScene behavior)
    game.hook_dispatcher.emit(.{ .scene_before_load = .{ .name = initial_scene.name, .allocator = allocator } });

    var scene = try Loader.load(initial_scene, ctx);
    defer scene.deinit();

    // Emit scene_load hook for initial scene (mirrors Game.setScene behavior)
    game.hook_dispatcher.emit(.{ .scene_load = .{ .name = initial_scene.name } });

    defer {
        // Only emit scene_unload for initial scene if no scene change occurred.
        // If game.setScene() was called, Game.deinit() handles the unload hook
        // for the current scene, so we shouldn't double-emit for initial_scene.
        if (game.getCurrentSceneName() == null) {
            game.hook_dispatcher.emit(.{ .scene_unload = .{ .name = initial_scene.name } });
        }
    }

    if (ci_test) return;

    while (game.isRunning()) {
        const dt = game.getDeltaTime();
        scene.update(dt);
        game.getPipeline().sync(game.getRegistry());

        const re = game.getRetainedEngine();
        re.beginFrame();
        re.render();
        game.processPendingScreenshot();
        re.endFrame();
    }
}
