// ============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT
// ============================================================================
// This file is generated by labelle-engine from project.labelle
// Project: mobile_physics_test
//
// Any manual changes will be overwritten on next generation.
//
// To regenerate: zig build generate
// To modify settings: edit project.labelle instead
//
// This project uses the sokol backend with callback-based architecture for iOS.
// The main loop is driven by sokol_app callbacks (init, frame, cleanup, event).
// Project configuration is embedded at compile time for iOS compatibility.
// ============================================================================

const std = @import("std");
const engine = @import("labelle-engine");
const ProjectConfig = engine.ProjectConfig;

// Sokol bindings - re-exported from engine for iOS callback architecture
const sokol = engine.sokol;
const sg = sokol.gfx;
const sgl = sokol.gl;
const sapp = sokol.app;

const bouncing_ball_prefab = @import("prefabs/bouncing_ball.zon");
const physics_sim_script = @import("scripts/physics_sim.zig");
const main_module = @This();
pub const Prefabs = engine.PrefabRegistry(.{
    .bouncing_ball = bouncing_ball_prefab,
});
pub const Components = engine.ComponentRegistry(struct {
    // Engine built-in components
    pub const Position = engine.Position;
    pub const Sprite = engine.Sprite;
    pub const Shape = engine.Shape;
    pub const Text = engine.Text;
    // Physics components (auto-included when physics is enabled)
    pub const RigidBody = engine.PhysicsComponents.RigidBody;
    pub const Collider = engine.PhysicsComponents.Collider;
    pub const Velocity = engine.PhysicsComponents.Velocity;
});
pub const Scripts = engine.ScriptRegistry(struct {
    pub const physics_sim = physics_sim_script;
});
const Game = engine.Game;

pub const Loader = engine.SceneLoader(Prefabs, Components, Scripts);
pub const initial_scene = @import("scenes/main.zon");

// Global state for sokol callback pattern
// Sokol uses callbacks, so we need global state accessible from init/frame/cleanup
const State = struct {
    allocator: std.mem.Allocator = undefined,
    game: ?*Game = null,
    scene: ?*engine.Scene = null,
    initialized: bool = false,
    should_quit: bool = false,
    ci_test: bool = false,
    frame_count: u32 = 0,
};

var state: State = .{};

// Allocated storage for game and scene (needed because sokol callbacks can't return errors)
var game_storage: Game = undefined;
var scene_storage: engine.Scene = undefined;

// Sokol app callbacks for iOS
export fn init() void {
    state.ci_test = std.posix.getenv("CI_TEST") != null;

    // Initialize sokol_gfx with sokol_app's rendering context
    sg.setup(.{
        .environment = sokol.glue.environment(),
        .logger = .{ .func = sokol.log.func },
    });

    // Initialize sokol_gl for 2D drawing (must be after sg.setup)
    sgl.setup(.{
        .logger = .{ .func = sokol.log.func },
    });

    // Use page allocator for simplicity in callback context
    state.allocator = std.heap.page_allocator;

    // Initialize game with embedded config (iOS doesn't load from filesystem)
    game_storage = Game.init(state.allocator, .{
        .window = .{
            .width = 800,
            .height = 600,
            .title = "Mobile Physics Test",
            .target_fps = 60,
        },
        .clear_color = .{ .r = 30, .g = 35, .b = 45 },
    }) catch |err| {
        std.debug.print("Failed to initialize game: {}\n", .{err});
        sapp.quit();
        return;
    };
    state.game = &game_storage;
    state.game.?.fixPointers();

    // Apply embedded camera configuration
    state.game.?.setCameraPosition(400.0, 300.0);
    state.game.?.setCameraZoom(1.00);

    const ctx = engine.SceneContext.init(state.game.?);

    // Emit scene_before_load hook for initial scene
    Game.HookDispatcher.emit(.{ .scene_before_load = .{ .name = initial_scene.name, .allocator = state.allocator } });

    // Load initial scene
    scene_storage = Loader.load(initial_scene, ctx) catch |err| {
        std.debug.print("Failed to load scene: {}\n", .{err});
        sapp.quit();
        return;
    };
    state.scene = &scene_storage;

    // Emit scene_load hook for initial scene
    Game.HookDispatcher.emit(.{ .scene_load = .{ .name = initial_scene.name } });

    state.initialized = true;
    std.debug.print("Sokol iOS backend initialized successfully!\n", .{});
    std.debug.print("Window size: {}x{}\n", .{ sapp.width(), sapp.height() });

    // For CI testing, we'll exit after a few frames (handled in frame callback)
}

export fn frame() void {
    if (!state.initialized or state.game == null or state.scene == null) return;

    // CI test mode: exit after 10 frames
    state.frame_count += 1;
    if (state.ci_test) {
        if (state.frame_count > 10) {
            state.should_quit = true;
            sapp.quit();
            return;
        }
    }

    // Get delta time from sokol
    const dt: f32 = @floatCast(sapp.frameDuration());

    // Update scene (runs scripts, etc.)
    state.scene.?.update(dt);

    // Sync ECS components to graphics
    state.game.?.getPipeline().sync(state.game.?.getRegistry());

    // Begin sokol render pass (required for sokol backend)
    var pass_action: sg.PassAction = .{};
    pass_action.colors[0] = .{
        .load_action = .CLEAR,
        .clear_value = .{ .r = 0.118, .g = 0.137, .b = 0.176, .a = 1.0 },
    };
    sg.beginPass(.{
        .action = pass_action,
        .swapchain = sokol.glue.swapchain(),
    });

    // Render using the retained engine
    const re = state.game.?.getRetainedEngine();
    re.beginFrame();
    re.render();
    re.endFrame();

    // End sokol render pass and commit
    sg.endPass();
    sg.commit();
}

export fn cleanup() void {
    // Emit scene_unload hook if we still have the initial scene
    if (state.initialized and state.game != null) {
        if (state.game.?.getCurrentSceneName() == null) {
            Game.HookDispatcher.emit(.{ .scene_unload = .{ .name = initial_scene.name } });
        }
    }

    // Cleanup scene
    if (state.scene) |scene| {
        scene.deinit();
        state.scene = null;
    }

    // Cleanup game
    if (state.game) |game| {
        game.deinit();
        state.game = null;
    }

    // Cleanup sokol in reverse order of initialization
    sgl.shutdown();
    sg.shutdown();

    std.debug.print("Sokol iOS backend cleanup complete.\n", .{});
}

export fn event(ev: ?*const sapp.Event) void {
    const e = ev orelse return;

    // iOS touch events can be handled here
    switch (e.type) {
        .TOUCHES_BEGAN, .TOUCHES_MOVED, .TOUCHES_ENDED, .TOUCHES_CANCELLED => {
            // Touch handling for iOS
            // TODO: Forward to game input system
        },
        .KEY_DOWN => {
            // Keyboard (if available)
            if (e.key_code == .ESCAPE) {
                sapp.quit();
            }
        },
        else => {},
    }
}

pub fn main() void {
    // Run sokol app with iOS-optimized settings
    sapp.run(.{
        .init_cb = init,
        .frame_cb = frame,
        .cleanup_cb = cleanup,
        .event_cb = event,
        .width = 800,
        .height = 600,
        .window_title = "Mobile Physics Test",
        .high_dpi = true,  // Enable Retina display support
        .icon = .{ .sokol_default = true },
        .logger = .{ .func = sokol.log.func },
    });
}
