//! Renderer/ECS-independent animation authoring. No dependency on the engine.
pub const Library = @import("library.zig").Library;
pub const Definition = @import("definition.zig").Definition;
pub const Clip = @import("definition.zig").Clip;
pub const FrameRange = @import("frame_range.zig").FrameRange;
pub const Marker = @import("marker.zig").Marker;
pub const MarkerCursor = @import("marker_cursor.zig").MarkerCursor;
pub const Occurrence = @import("marker_cursor.zig").Occurrence;
pub const BoundaryMode = @import("marker_cursor.zig").BoundaryMode;

pub const anim_timing_mod = @import("anim_timing.zig");
pub const animation_def_mod = @import("animation_def.zig");
pub const animation_def_runtime_mod = @import("animation_def_runtime.zig");
pub const animation_state_mod = @import("animation_state.zig");
pub const animation_events_mod = @import("animation_events.zig");
pub const sprite_animation_mod = @import("sprite_animation.zig");
pub const sprite_by_field_mod = @import("sprite_by_field.zig");
pub const AdvanceMode = anim_timing_mod.AdvanceMode;
pub const AnimationDef = animation_def_mod.AnimationDef;
pub const AnimationState = animation_state_mod.AnimationState;
pub const advanceAny = animation_state_mod.advanceAny;
pub const transitionAny = animation_state_mod.transitionAny;
pub const requestTransitionAny = animation_state_mod.requestTransitionAny;
pub const applyPendingAny = animation_state_mod.applyPendingAny;
pub const AnimMode = animation_def_mod.Mode; // deprecated alias of AdvanceMode
pub const AnimClipMeta = animation_def_mod.ClipMeta;
pub const AnimSwitchMode = animation_state_mod.SwitchMode;
pub const AnimTransitionRule = animation_def_mod.TransitionRule;
pub const RuntimeAnimationDef = animation_def_runtime_mod.RuntimeAnimationDef;
pub const AnimDefSource = animation_def_runtime_mod.AnimDefSource;
pub const refreshState = animation_def_runtime_mod.refreshState;
pub const ReloadWatcher = animation_def_runtime_mod.ReloadWatcher;
pub const RuntimeAnimDefs = animation_def_runtime_mod.RuntimeAnimDefs;
pub const AnimFrameEntry = animation_def_mod.FrameEntry;
pub const AnimMarkerHit = animation_events_mod.AnimMarkerHit;
pub const AnimClipEnd = animation_events_mod.AnimClipEnd;
pub const AnimLoopEnd = animation_events_mod.AnimLoopEnd;
pub const PendingAnimEvent = animation_events_mod.PendingAnimEvent;
pub const AnimPendingBuf = animation_events_mod.PendingBuf;
pub const AnimEventKind = animation_events_mod.PendingKind;
pub const anim_pending_cap = animation_events_mod.max_pending;
pub const SpriteAnimation = sprite_animation_mod.SpriteAnimation;
pub const SpriteAnimationMode = sprite_animation_mod.AnimationMode; // deprecated alias of BoundaryMode
pub const SpriteByField = sprite_by_field_mod.SpriteByField;
pub const SpriteByFieldSource = sprite_by_field_mod.SpriteByFieldSource;
