const std = @import("std");
const core = @import("labelle-core");

const Position = core.Position;
const MockEcsBackend = core.MockEcsBackend;
const HookDispatcher = core.HookDispatcher;
const hooks_types = @import("hooks_types.zig");
const ComponentPayload = hooks_types.ComponentPayload;
const VisualType = core.VisualType;
const ParentComponent = core.ParentComponent;
const ChildrenComponent = core.ChildrenComponent;
const PrefabInstance = core.PrefabInstance;
const PrefabChild = core.PrefabChild;

const atlas_mod = @import("atlas.zig");
const assets_mod = @import("assets/mod.zig");
const asset_manifest_mod = @import("asset_manifest.zig");
const game_log_mod = @import("game_log.zig");
const preview_mode_mod = @import("preview_mode.zig");
const scheduler_mod = @import("scheduler.zig");
const controller_manager_mod = @import("controller_manager.zig");

const hierarchy = @import("game/hierarchy.zig");
const gizmo_draws_mod = @import("game/gizmo_draws.zig");
const input_types = @import("input_types.zig");
const builtin = @import("builtin");

/// Fixed scratch capacity for draining gamepad hotplug events per tick
/// (core#18). The drain source writes at most this many `GamepadEvent`s
/// into a stack buffer; any surplus stays queued and is picked up on the
/// next tick. 16 comfortably covers a frame's worth of connect/disconnect
/// churn without a heap allocation.
const gamepad_drain_capacity = 16;

// Mixin modules — domain-specific method groups
const visuals_mixin = @import("game/visuals.zig");
const input_mixin = @import("game/input_mixin.zig");
const audio_mixin = @import("game/audio_mixin.zig");
const video_mixin = @import("game/video_mixin.zig");
const gui_mixin = @import("game/gui_mixin.zig");
const gizmo_mixin = @import("game/gizmo_mixin.zig");
const mesh_mixin = @import("game/mesh_mixin.zig");
const ui_kit_mixin = @import("game/ui_kit_mixin.zig");
const ui_draw_list_mod = @import("ui_draw_list.zig");
const render_target_mixin = @import("game/render_target_mixin.zig");
const post_fx_mixin = @import("game/post_fx_mixin.zig");
const scene_mixin = @import("game/scene_mixin.zig");
const save_load_mixin = @import("game/save_load_mixin.zig");
const state_mixin = @import("game/state_mixin.zig");
const atlas_mixin = @import("game/atlas_mixin.zig");
const world_mixin = @import("game/world_mixin.zig");
const lifecycle_mixin = @import("game/lifecycle_mixin.zig");
const components_mixin = @import("game/components_mixin.zig");
const entity_mixin = @import("game/entity_mixin.zig");
const scene_runtime_mixin = @import("game/scene_runtime_mixin.zig");
const input_events_mixin = @import("game/input_events_mixin.zig");
const events_mixin = @import("game/events_mixin.zig");
const editor_command_mixin = @import("game/editor_command_mixin.zig");
const loop_mixin = @import("game/loop_mixin.zig");
const fixed_timestep_mixin = @import("game/fixed_timestep_mixin.zig");
const misc_mixin = @import("game/misc_mixin.zig");
const animation_runtime_mixin = @import("game/animation_runtime_mixin.zig");
const animation_def_runtime = @import("animation_def_runtime.zig");
const prefab_runtime_mixin = @import("game/prefab_runtime_mixin.zig");
const roster_mod = @import("game/roster.zig");
const game_init_mod = @import("game/game_init.zig");
const tilemap_mod = @import("tilemap.zig");
const tilemap_runtime = @import("tilemap_runtime.zig");
const tilemap_mixin = @import("game/tilemap_mixin.zig");
const camera_mod = @import("camera.zig");
const image_component_mod = @import("image_component.zig");
const camera_mixin = @import("game/camera_mixin.zig");
const emitter_mod = @import("emitter.zig");
const emitter_mixin = @import("game/emitter_mixin.zig");
const particles_mod = @import("particles.zig");
const frame_profiler_mod = @import("frame_profiler.zig");

/// Full game configuration — the assembler fills ALL comptime slots.
/// RenderImpl is a renderer plugin (e.g. gfx.GfxRenderer) satisfying RenderInterface.
/// The engine does NOT depend on labelle-gfx — it accesses component types through RenderImpl.
///
/// **Y-axis convention.** This entry point keeps the historical positional
/// signature (the assembler's `engine.GameConfig(...)` call ends at
/// `GameEvents,`) and defaults the project's logical Y-axis to `.up` — today's
/// historical behavior (labelle-engine#642). This is the **code-level**
/// default and exists purely for transition safety: now that the renderer
/// *reads* `Game.y_axis` (engine#642 threads it into `GfxRendererWith`), a
/// game generated by the *old* assembler still calls `GameConfig` with no
/// explicit axis. If that fell back to `.down` the renderer would stop
/// flipping and the game would render upside-down. Falling back to `.up`
/// keeps such games bit-identical to pre-#642.
///
/// `.down` remains the **project-config** default (the assembler's unset-guard
/// + `labelle-init`, RFC §3, Q1→(b)) — never the engine code default. A
/// project that wants `.down` (screen-native) goes through
/// `GameConfigWithYAxis`, which the assembler (#370) emits once it parses
/// `.y_axis` from `project.labelle`. Threading a convention this way is purely
/// additive: existing generated games keep calling `GameConfig` unchanged.
pub fn GameConfig(
    comptime RenderImpl: type,
    comptime EcsImpl: type,
    comptime InputImpl: type,
    comptime AudioImpl: type,
    comptime VideoImpl: type,
    comptime GuiImpl: type,
    comptime Hooks: type,
    comptime LogSinkImpl: type,
    comptime ComponentsType: type,
    comptime GizmoCategoriesSlice: anytype,
    comptime GameEventsParam: type,
) type {
    return GameConfigWithYAxis(
        RenderImpl,
        EcsImpl,
        InputImpl,
        AudioImpl,
        VideoImpl,
        GuiImpl,
        Hooks,
        LogSinkImpl,
        ComponentsType,
        GizmoCategoriesSlice,
        GameEventsParam,
        // Code-level default — `.up` preserves today's renderer flip for
        // old-assembler games that call `GameConfig` with no explicit axis
        // (engine#642). The `.down` project-config default lives in the
        // assembler/labelle-init, not here.
        .up,
    );
}

/// Y-axis-aware game configuration — identical to `GameConfig` but with an
/// explicit project Y-axis convention as the trailing comptime slot. The
/// assembler emits this entry point once it parses `.y_axis` from
/// `project.labelle` (labelle-engine#639 / assembler #370); until then
/// `GameConfig` delegates here with the `.down` default so the threading is
/// already in place and only the assembler's emitted call needs to change.
///
/// `y_axis_param` is surfaced as the comptime constant `Game.y_axis` (and the
/// `game.yAxis()` accessor), and is consumed by `screenToLogical` — the
/// axis-aware picking path — via core's canonical `screenToLogicalY` transform.
pub fn GameConfigWithYAxis(
    comptime RenderImpl: type,
    comptime EcsImpl: type,
    comptime InputImpl: type,
    comptime AudioImpl: type,
    comptime VideoImpl: type,
    comptime GuiImpl: type,
    comptime Hooks: type,
    comptime LogSinkImpl: type,
    comptime ComponentsType: type,
    comptime GizmoCategoriesSlice: anytype,
    comptime GameEventsParam: type,
    comptime y_axis_param: core.YAxis,
) type {
    // Validate renderer satisfies the contract
    _ = core.RenderInterface(RenderImpl);

    const Entity = EcsImpl.Entity;
    const Sprite = RenderImpl.Sprite;
    const Shape = RenderImpl.Shape;
    const Text = if (@hasDecl(RenderImpl, "Text")) RenderImpl.Text else void;
    const Icon = if (@hasDecl(RenderImpl, "Icon")) RenderImpl.Icon else void;
    const Parent = ParentComponent(Entity);
    const Children = ChildrenComponent(Entity);
    const PrefabChildT = PrefabChild(Entity);
    const EnginePayload = hooks_types.HookPayload(Entity);
    const has_events = GameEventsParam != void;
    const Payload = if (has_events) core.MergeHookPayloads(.{ EnginePayload, GameEventsParam }) else EnginePayload;
    const has_hooks = Hooks != void;
    const HooksIsMerged = has_hooks and @typeInfo(Hooks) == .pointer and @hasDecl(@typeInfo(Hooks).pointer.child, "emit");
    const HooksField = if (!has_hooks)
        void
    else if (HooksIsMerged)
        ?Hooks
    else
        ?HookDispatcher(Payload, Hooks, .{});
    const EventBuffer = if (has_events) std.ArrayList(GameEventsParam) else void;

    return struct {
        const Self = @This();
        const is_debug = builtin.mode == .Debug;

        // Debug-only: entity tombstone tracking (#419, #420)
        pub const tombstone_size = 64;
        pub const TombstoneEntry = struct { entity: Entity, frame: u64 };

        pub const EntityType = Entity;

        // ── Roster cache (#653, Packs Phase 2 / #657) ─────────────
        // The full design + borrowed-slice lifetime contract live in
        // `game/roster.zig` (facade split). Game owns the two state
        // fields (`roster_generation`, `roster_cache`); the mixin owns
        // the logic.
        const RosterSlot = roster_mod.Slot(Entity);

        /// Runtime timer wheel for flow `Delay` nodes (#25 Stage 2). Keyed
        /// on the engine `Entity` type; fires pause-aware callbacks against
        /// the gameplay clock. See `src/scheduler.zig`.
        pub const SchedulerType = scheduler_mod.Scheduler(Entity);
        /// Re-export the game-event type so plugins can reflect against
        /// `Game.GameEvents` (e.g. labelle-box2d's `emitGameEvent`).
        /// Without this, plugin events compile to a silent no-op in every
        /// assembled game (labelle-engine#601).
        ///
        /// Contract: this is the *union* for games that declare events, but
        /// **`void`** for event-less games (`GameWith(Hooks)`). So consumers
        /// MUST gate on `@hasDecl(Game, "GameEvents") and
        /// @typeInfo(Game.GameEvents) == .@"union"` — not `@hasDecl` alone,
        /// which is now always true. (`usingnamespace` would let us omit the
        /// decl for `void`, but it's removed in Zig 0.16.) labelle-box2d
        /// already does the union check.
        pub const GameEvents = GameEventsParam;
        // Internal event-dispatch types/flags surfaced for the events
        // mixin (`game/events_mixin.zig`). These mirror the identically-
        // named consts in `GameConfig`'s function body bit-for-bit (same
        // expressions over the same in-scope params), so the mixin and the
        // struct body share one comptime definition. Re-derived rather than
        // aliased because a struct decl can't reference an outer const of
        // the same name without a dependency loop.
        pub const PayloadExport = Payload;
        pub const EventBufferExport = EventBuffer;
        pub const has_events_export = has_events;
        pub const has_hooks_export = has_hooks;
        // For the lifecycle mixin's `setHooks` (mirrors the function-body
        // consts of the same role; see PayloadExport rationale).
        pub const HooksParam = Hooks;
        pub const HooksIsMergedExport = HooksIsMerged;
        pub const EcsBackend = EcsImpl;
        pub const SpriteComp = Sprite;
        /// Engine built-in `Image` component — standalone-PNG entity backed by
        /// `AssetCatalog` (#568). Distinct from `SpriteComp` (atlas sprites)
        /// and from the imgui `gui_types.Image`. See `src/image_component.zig`.
        pub const ImageComp = image_component_mod.Image;
        pub const ShapeComp = Shape;
        pub const TextComp = Text;
        pub const IconComp = Icon;
        pub const ParentComp = Parent;
        pub const ChildrenComp = Children;
        pub const PrefabInstanceComp = PrefabInstance;
        pub const PrefabChildComp = PrefabChildT;

        // ── Camera (camera-prefabs MVP, #714) ────────────────────
        /// Engine built-in `Camera` component — the authored / seed camera
        /// state (`zoom` + optional inert `viewport`; the camera's world
        /// center is its `Position`). Handled by dedicated built-in channels
        /// (scene loader, seed/apply sync, digest, editor bridge) — NOT a
        /// `ComponentRegistry` component. See `src/camera.zig`.
        pub const CameraComp = camera_mod.Camera;
        /// True when the engine's built-in `Camera` feature is ACTIVE — i.e.
        /// the project did NOT register its own `Camera` in its
        /// `ComponentRegistry`. When a project registers `Camera`, every
        /// built-in Camera channel (seed / apply-while-paused / digest / the
        /// `editor_set_component` bridge / save-load) DEFERS to the project's
        /// component so the two never fight over the name — mirroring the
        /// scene-loader `!Components.has("Camera")` guard in
        /// `jsonc/component_apply.zig`. The `@hasDecl` guard keeps this sound
        /// for any `ComponentRegistry` shape that predates a `has` decl.
        pub const camera_is_builtin = !(@hasDecl(ComponentsType, "has") and ComponentsType.has("Camera"));

        // ── Tilemap (T2 Phase 2) ─────────────────────────────────
        /// Engine built-in `Tilemap` component (references a `.tmx` asset
        /// by name). Handled by dedicated built-in channels (scene loader,
        /// save/load, digest) — NOT a `ComponentRegistry` component.
        pub const TilemapComp = tilemap_mod.Tilemap;
        /// True when the renderer plugin exposes gfx's tilemap seam
        /// (`RenderImpl.TileMapRendererType` + the shared texture path).
        /// Gates the decoded-map runtime + post-sprite pass; when false the
        /// component still attaches but renders nothing (stub renderers).
        pub const tilemap_supported = tilemap_runtime.supported(RenderImpl);
        /// Per-entity decoded-map + draw-pass renderer (heap-owned by the
        /// side table). `void` on renderers without the tilemap seam.
        pub const TilemapRuntimeType = if (tilemap_supported)
            tilemap_runtime.Runtime(RenderImpl)
        else
            void;

        /// The renderer's layer enum (`RenderImpl.Layer`, gfx's
        /// `LayerEnum`), or `void` when the renderer doesn't expose one.
        /// The T3 tilemap Z-interleave binds `.tmx` layers to engine layers
        /// by matching a `.tmx` layer name to a `@tagName` of this enum.
        pub const RenderLayerEnum = if (@hasDecl(RenderImpl, "Layer")) RenderImpl.Layer else void;

        /// True when the tilemap Z-interleave (T3) is available. When false
        /// the engine falls back to the T2 whole-stack pre-sprite background
        /// pass (`renderTilemaps` + `renderer.render()`), so stub / older /
        /// non-standard renderers are unaffected.
        ///
        /// Requires, in order (short-circuited so a later reflection is never
        /// analyzed when an earlier guard fails — same defensive-comptime
        /// spirit as `tilemap_runtime.hasReflectableSeam`, gfx #711 review):
        ///   1. the decoded-map seam (`tilemap_supported`);
        ///   2. the per-layer render hook `renderWithLayerHook` (gfx ≥1.22.0);
        ///   3. a `Layer` decl that is a genuine `enum` type (NOT `void` / a
        ///      non-enum stub) exposing `config()` — the two things the
        ///      interleave path calls on it (`stringToEnum(Layer, …)` and
        ///      `layer.config().space`). Without this a renderer that declares
        ///      `renderWithLayerHook` but has `Layer = void` (or a non-config
        ///      type) would route into a path that can't compile.
        pub const tilemap_interleave_supported = interleaveSupported();

        fn interleaveSupported() bool {
            if (!tilemap_supported) return false;
            if (!@hasDecl(RenderImpl, "renderWithLayerHook")) return false;
            if (!@hasDecl(RenderImpl, "Layer")) return false;
            const L = RenderImpl.Layer;
            if (@typeInfo(L) != .@"enum") return false;
            if (!@hasDecl(L, "config")) return false;
            return true;
        }

        /// True when the tilemap BACKGROUND (unbound `.tmx` layers) can be
        /// drawn PER active camera: the renderer exposes the dual-hook
        /// `renderWithLayerHooks` (gfx ≥1.24.0), whose `on_before_layers`
        /// callback runs once per active camera inside that camera's transform
        /// + viewport scissor, before the sprite stack. Builds on
        /// `tilemap_interleave_supported`. When false but interleave IS
        /// supported (a renderer with only the older single-callback
        /// `renderWithLayerHook`, gfx 1.22–1.23) the background falls back to
        /// the single primary-camera pass; BOUND layers are per-camera either
        /// way. `@hasDecl` on the valid `RenderImpl` is always safe, so a
        /// plain `and` suffices here.
        pub const tilemap_percamera_background_supported = tilemap_interleave_supported and
            @hasDecl(RenderImpl, "renderWithLayerHooks");

        // ── Particles / Emitter (#750) ───────────────────────────────
        /// Engine built-in `Emitter` component (authors a particle emitter;
        /// see `src/emitter.zig`). Handled by dedicated built-in channels
        /// (scene loader, side-table runtime) — NOT a `ComponentRegistry`
        /// component, unless a project registers its own `Emitter`, which
        /// takes precedence (the scene-loader branch is gated on
        /// `!Components.has("Emitter")`).
        pub const EmitterComp = emitter_mod.Emitter;
        /// True when the project did NOT register its own `Emitter` — i.e.
        /// the engine's built-in emitter channel is active. Mirrors
        /// `camera_is_builtin`.
        pub const emitter_is_builtin =
            !(@hasDecl(ComponentsType, "has") and ComponentsType.has("Emitter"));

        pub const Input = @import("input.zig").InputInterface(InputImpl);

        /// True when the active input backend itself declares
        /// `pollGamepadEvents` (core#18). We probe `InputImpl` — the raw
        /// backend — NOT `Self.Input`, whose wrapper method always exists
        /// (it just falls back to returning 0). This single comptime flag
        /// picks the gamepad hotplug source and guarantees we never run
        /// BOTH the backend and the per-OS `gamepad_source` (no
        /// double-source / duplicate events):
        ///   - backend declares it  → drain `Self.Input.pollGamepadEvents`
        ///   - backend does NOT     → drain `core.gamepad_source.pollEvents`
        ///                            (and run its `init`/`deinit`)
        pub const backend_polls_gamepads = @hasDecl(InputImpl, "pollGamepadEvents");

        /// True only when we actually need the per-OS `gamepad_source`:
        /// the backend doesn't poll AND a flow listens for gamepad events.
        /// Gates the source's `init`/`deinit` lifecycle calls so an
        /// event-less game (or one on a backend that polls natively) never
        /// touches the OS source — keeping the feature zero-cost.
        pub const uses_os_gamepad_source = !backend_polls_gamepads and gamepad_events_wanted;

        pub const Audio = @import("audio.zig").AudioInterface(AudioImpl);
        pub const Video = core.VideoInterface(VideoImpl);
        pub const Gui = @import("gui.zig").GuiInterface(GuiImpl);
        pub const GizmoDraw = gizmo_draws_mod.GizmoDraw;
        /// Blend mode for `drawMesh` — re-exported from labelle-core's backend
        /// contract (labelle-gfx#290). `labelle-spine` maps `spBlendMode`
        /// straight onto this enum.
        pub const BlendMode = core.BlendMode;
        pub const Log = game_log_mod.GameLog(LogSinkImpl, core.log.default_min_level);
        /// Component registry — for debug introspection by plugins.
        pub const ComponentRegistry = ComponentsType;
        /// Gizmo categories discovered from plugins at comptime.
        pub const gizmo_categories = GizmoCategoriesSlice;

        /// The project's logical Y-axis convention (labelle-engine#639/#642,
        /// RFC §3). `.down` means `y = 0` is the TOP and +Y grows downward —
        /// screen-native, the renderer flip is identity. `.up` (the
        /// `GameConfig` code default) means `y = 0` is the BOTTOM and +Y grows
        /// upward — today's behavior, the renderer flips on the way out.
        /// Consumed by both `screenToLogical` (axis-aware picking, input) and
        /// the gfx renderer/camera (`GfxRendererWith(..., Game.y_axis)`,
        /// output) so the two paths can never diverge (engine#642). Exposed at
        /// runtime via `yAxis()`.
        pub const y_axis: core.YAxis = y_axis_param;

        // ── Mixin types ──────────────────────────────────────────
        const Visuals = visuals_mixin.Mixin(Self);
        const InputMixin = input_mixin.Mixin(Self);
        const AudioMixin = audio_mixin.Mixin(Self);
        const VideoMixin = video_mixin.Mixin(Self);
        const GuiMixin = gui_mixin.Mixin(Self);
        const GizmoMixin = gizmo_mixin.Mixin(Self);
        const MeshMixin = mesh_mixin.Mixin(Self);
        const UiKitMixin = ui_kit_mixin.Mixin(Self);
        const RenderTargetMixin = render_target_mixin.Mixin(Self);
        const PostFxMixin = post_fx_mixin.Mixin(Self);
        const SceneMixin = scene_mixin.Mixin(Self);
        const SaveLoadMixin = save_load_mixin.Mixin(Self);
        const StateMixin = state_mixin.Mixin(Self);
        const AtlasMixin = atlas_mixin.Mixin(Self);
        const WorldMixin = world_mixin.Mixin(Self);
        const LifecycleMixin = lifecycle_mixin.Mixin(Self);
        const ComponentsMixin = components_mixin.Mixin(Self);
        const EntityMixin = entity_mixin.Mixin(Self);
        const SceneRuntimeMixin = scene_runtime_mixin.Mixin(Self);
        const InputEventsMixin = input_events_mixin.Mixin(Self);
        const EventsMixin = events_mixin.Mixin(Self);
        const EditorCommandMixin = editor_command_mixin.Mixin(Self);
        const LoopMixin = loop_mixin.Mixin(Self);
        const FixedTimestepMixin = fixed_timestep_mixin.Mixin(Self);
        const MiscMixin = misc_mixin.Mixin(Self);
        const AnimationRuntimeMixin = animation_runtime_mixin.Mixin(Self);
        const PrefabRuntimeMixin = prefab_runtime_mixin.Mixin(Self);
        const RosterMixin = roster_mod.Mixin(Self);
        const TilemapMixin = tilemap_mixin.Mixin(Self);
        const CameraMixin = camera_mixin.Mixin(Self);
        const EmitterMixin = emitter_mixin.Mixin(Self);
        // VideoImpl/AudioImpl are `GameConfig` fn params (not `Self`
        // decls), so the construction mixin takes them explicitly.
        const InitMixin = game_init_mod.Mixin(Self, VideoImpl, AudioImpl);

        /// Scene lifecycle hooks
        pub const SceneHooks = struct {
            onLoad: ?*const fn (*Self) void = null,
            onUnload: ?*const fn (*Self) void = null,
        };

        /// Controls how `setScene` reacts when the new scene's asset
        /// manifest contains a `.failed` entry. See
        /// `Self.asset_failure_policy`.
        pub const AssetFailurePolicy = enum { fatal, warn, silent };

        pub const SceneEntry = struct {
            loader_fn: *const fn (*Self) anyerror!void,
            hooks: SceneHooks,
            /// Declared asset manifest for this scene — the slice of asset names
            /// the scene needs loaded before it runs. Populated by the assembler
            /// from each scene's `"assets": [...]` block (see Asset Streaming
            /// RFC #437 / issue #445). Defaults to an empty slice for scenes
            /// registered via the legacy (non-manifest) path; scripts can then
            /// do `game.scenes.get("main").?.assets` without a null check.
            assets: []const []const u8 = &.{},
            /// Optional state the scene wants the game to be in when it loads.
            /// Both `setScene` and `setSceneAtomic` call `setState(initial_state.?)`
            /// after the scene's assets are ready and the entity load finishes.
            /// Populated by the assembler from each scene's
            /// `"initial_state": "<name>"` field (issue #500). `null` (default)
            /// means the scene doesn't request a state change — current behavior
            /// preserved.
            ///
            /// Lifetime: stored by reference, must outlive the `Game`. The
            /// assembler emits a string-literal slice, which is program-lifetime.
            initial_state: ?[]const u8 = null,
            /// Raw JSONC scene source, for **sprite-based asset inference**
            /// (#563). Populated by the assembler via `setSceneSource` — a
            /// program-lifetime `@embedFile` borrow of the scene's `.jsonc`.
            /// When a scene declares NO explicit `assets` manifest and this
            /// source is present, `setScene`/`setSceneAtomic` walk it against
            /// the runtime reverse index (`inferAssetsFromSource`) to *derive*
            /// the manifest, then cache the result into `assets` above so the
            /// acquire/release/gate path behaves exactly as if it had been
            /// declared. `null` (default) preserves pre-inference behavior
            /// (the Debug eager-load-everything fallback still applies).
            ///
            /// Lifetime: stored by reference, must outlive the `Game`.
            source: ?[]const u8 = null,
        };

        /// Runtime JSONC scene path info.
        pub const JsoncSceneInfo = struct {
            scene_path: []const u8,
            prefab_dir: []const u8,
        };

        pub const FrameCallback = *const fn (*Self, f32) void;

        /// A world bundles ECS, renderer, sprite cache, and arena.
        /// The active world is a heap-allocated pointer for stable references.
        /// Inactive worlds live in the `worlds` map as heap pointers.
        pub const World = struct {
            ecs_backend: EcsImpl,
            renderer: RenderImpl,
            sprite_cache: atlas_mod.SpriteCache,
            nested_entity_arena: std.heap.ArenaAllocator,

            pub fn init(allocator: std.mem.Allocator) World {
                return .{
                    .ecs_backend = EcsImpl.init(allocator),
                    .renderer = RenderImpl.init(allocator),
                    .sprite_cache = atlas_mod.SpriteCache.init(allocator),
                    .nested_entity_arena = std.heap.ArenaAllocator.init(allocator),
                };
            }

            pub fn deinit(self: *World) void {
                self.nested_entity_arena.deinit();
                self.sprite_cache.deinit();
                self.renderer.deinit();
                self.ecs_backend.deinit();
            }
        };

        allocator: std.mem.Allocator,
        active_world: *World,
        /// Backward-compatible ECS access — always points to active world's ECS.
        ecs_backend: *EcsImpl = undefined,
        /// Backward-compatible renderer access — always points to active world's renderer.
        renderer: *RenderImpl = undefined,
        worlds: std.StringHashMap(*World),
        active_world_name: ?[]const u8 = null,
        atlas_manager: atlas_mod.TextureManager,
        /// Streaming asset catalog — register + refcounted acquire/release
        /// for atlases, audio, fonts, etc. Worker thread is spawned lazily
        /// on the first `acquire` (see `assets/catalog.zig`), so wiring
        /// this eagerly in `Game.init` is near-free for games that never
        /// stream anything. Scripts call `game.assets.acquire(...)`,
        /// `game.assets.progress(...)`, etc. directly.
        ///
        /// The `loadAtlas*` family in this file pumps image decodes
        /// through this catalog instead of calling
        /// `renderer.loadTextureFromMemory` on the main thread — see
        /// `loadAtlasIfNeededImpl` below. Every asset registered through
        /// `registerAtlasFromMemory` / `loadAtlasFromMemory` gets a
        /// parallel entry here keyed by the same name so the PNG decode
        /// runs off-thread even for the legacy eager path.
        ///
        /// `pump()` is the caller's responsibility for now: the engine
        /// tick does NOT call it automatically. Automatic per-frame
        /// pumping is deferred to the scene-hooks ticket (#444) so the
        /// design can be settled alongside scene-manifest auto-acquire.
        assets: assets_mod.AssetCatalog,
        hooks: HooksField = if (has_hooks) null else {},
        event_buffer: EventBuffer = if (has_events) .empty else {},

        // Scene management
        scenes: std.StringHashMap(SceneEntry),
        jsonc_scenes: std.StringHashMap(JsoncSceneInfo),
        /// Embedded JSONC sources keyed by their include-relative path
        /// (e.g. `"scenes/obstacles.jsonc"`). Mirrors the prefab cache
        /// pattern: when a scene declares `"include": [...]`, the JSONC
        /// loader looks here BEFORE falling back to `std.fs.cwd().openFile`,
        /// so WASM/Android builds (no project directory in cwd) can still
        /// resolve nested scene fragments. Populated by the assembler-
        /// generated `addEmbeddedSceneSource` calls in `main()` / `init()`.
        /// Keys are owned (dupe'd via `self.allocator`); values are
        /// program-lifetime borrows of `@embedFile` slices and are NOT
        /// freed by the map.
        embedded_scene_sources: std.StringHashMap([]const u8),
        /// Embedded tilemap-asset bytes (T2 Phase 2), keyed by asset name:
        /// both the `.tmx` documents (looked up by `Tilemap.asset_name`)
        /// and each tileset image (looked up by its `image_source`). Keys
        /// are owned (dup'd); values are program-lifetime `@embedFile`
        /// borrows, never freed by the map. The assembler emits registration
        /// calls in `init()` (Phase 4); see `addEmbeddedTilemapAsset`.
        embedded_tilemap_sources: std.StringHashMap([]const u8),
        /// Per-entity decoded-map + draw-pass renderers (T2 Phase 2). Heap
        /// pointers so the gfx tilemap renderer's `*const TileMap` into the
        /// runtime stays stable. `void` on renderers without the tilemap
        /// seam. Owned here; freed in `deinitTilemaps` / `releaseTilemap`.
        ///
        /// **Single-world scope (T2 limitation, F2 / #704).** This table is
        /// keyed on the Game and is NOT swapped with `active_world`, so its
        /// entity ids belong to whichever world was active when
        /// `addTilemap` ran. `resetEcsBackend` (scene swap / `loadGameState`)
        /// clears it via `clearTilemaps`, so the common single-world path is
        /// safe. A raw world *swap* (multiple live worlds) could leave a
        /// shelved world's ids here; `renderTilemaps` guards against drawing
        /// them by reaping any id that isn't `Tilemap`-bearing in the
        /// CURRENTLY active ECS. Proper per-world scoping (own the table on
        /// `World`, clean it in `destroyWorld`) is tracked in #704.
        tilemaps: if (tilemap_supported) std.AutoHashMap(Entity, *TilemapRuntimeType) else void,
        /// Per-entity particle sims for `Emitter` components (#750), keyed by
        /// entity. A `*ParticleSystem` owns a heap pool, so it can't live in
        /// the ECS; the `particles_tick` creates one per emitter on first
        /// sight. Renderer-agnostic (pure CPU sim), so — unlike `tilemaps` —
        /// this is always present. `resetEcsBackend` clears it via
        /// `clearParticleSystems` (entity ids die with the ECS reset).
        particle_systems: std.AutoHashMap(Entity, *particles_mod.ParticleSystem),
        /// Runtime scene-source overrides (labelle-studio Play mode /
        /// `editor_api`). Keyed by scene NAME (e.g. `"main"`); the JSONC
        /// loader consults this map BEFORE the embedded/compiled source
        /// on every load — `loadSceneFromSource` matches the name of the
        /// scene currently being loaded (`loading_scene_name`),
        /// `loadSceneFile` matches the include path exactly and then by
        /// stem (so an override for `"frag"` also replaces
        /// `"scenes/frag.jsonc"`). Unlike `embedded_scene_sources`, BOTH
        /// keys and values are owned copies (dupe'd via `self.allocator`);
        /// replacing an entry frees the previous source. See
        /// `setSceneSourceOverride` / `sceneSourceOverride`.
        scene_source_overrides: std.StringHashMap([]const u8),
        /// Runtime animation-def overrides (labelle-studio Play mode /
        /// `editor_api.editor_load_animation_def`, engine#672). Keyed by
        /// def name (the `.zon` stem, `"worker"`); game code consults
        /// `runtimeAnimDef` before its comptime table. See
        /// `game/animation_runtime_mixin.zig` for the refresh convention
        /// and `RuntimeAnimDefs` for the retire-don't-free ownership
        /// story. Empty (and cost-free) outside editor-preview hosts.
        runtime_anim_defs: animation_def_runtime.RuntimeAnimDefs,
        /// Name of the scene whose registered `loader_fn` is currently
        /// executing. Set by `setScene` / `setSceneAtomic` / the
        /// hot-reload path around the loader call ONLY — a borrow of the
        /// caller's name slice, valid strictly for the duration of the
        /// load. Lets `loadSceneFromSource` (which receives bytes, not a
        /// name) resolve the scene-source override for the right scene.
        loading_scene_name: ?[]const u8 = null,
        /// Entities created by the active scene's loader (e.g. the JSONC
        /// bridge). `unloadCurrentScene` destroys everything in this list
        /// on scene swap so entities from the outgoing scene don't leak
        /// into the incoming one. Loaders MUST call `trackSceneEntity`
        /// for every entity they create.
        scene_entities: std.ArrayList(Entity) = .empty,
        /// Set for the duration of a full scene-entity drain
        /// The entity currently being drained by `unloadCurrentScene`.
        /// `untrackSceneEntity` skips its O(N) swap-remove scan ONLY for
        /// this exact entity: the drain already `pop()`-ed it off the
        /// list, so the per-entity `destroyEntityOnly → untrackSceneEntity`
        /// self-scan would be pure O(N²) waste. A destroy-hook that
        /// destroys a *different* tracked entity (a sibling) still untracks
        /// it normally — so the drain won't pop an already-destroyed
        /// sibling a second time (double-destroy). See `unloadCurrentScene`
        /// (#630).
        current_teardown_entity: ?Entity = null,
        current_scene_name: ?[]const u8 = null,
        pending_scene_change: ?[]const u8 = null,
        pending_scene_atomic: bool = false,

        /// Phase 2 of the Asset Streaming RFC (#437). Tracks the
        /// scene name we have already called `assets.acquire()` for
        /// from inside `setScene` / `setSceneAtomic`. The transition
        /// is poll-driven: if the manifest is not yet `allReady`,
        /// `setScene` returns early and the script keeps calling it
        /// every frame. `pending_scene_assets` is the idempotency
        /// guard — without it we would re-acquire on every frame
        /// and the refcount would never come back to zero.
        ///
        /// Cleared after the swap completes (success path) or after
        /// an explicit abort (`scene_assets_release_pending`).
        pending_scene_assets: ?[]const u8 = null,

        /// Sprite-based asset-inference reverse index (#563), built lazily
        /// the first time a manifest-less scene with a `source` is loaded.
        /// Maps every atlas sprite path (and standalone image name) currently
        /// known to the engine to its providing resource bundle, so
        /// `inferAssetsFromSource` can derive a scene's manifest from its
        /// `Sprite`/`Image` references. `null` until first needed (zero cost
        /// for games that declare every manifest explicitly). Freed on
        /// `deinit`. See `scene_mixin.ensureReverseIndex`.
        reverse_index: ?asset_manifest_mod.ReverseIndex = null,

        /// Owns the name copies of every *inferred* scene manifest (#563).
        /// When `setScene` derives a manifest for a manifest-less scene, the
        /// resulting `InferredManifest` is parked here and its stable slice is
        /// cached onto `SceneEntry.assets`; this list keeps those name dupes
        /// alive for the `Game`'s lifetime so the cached slice never dangles.
        /// Each entry is `deinit`'d on `Game.deinit`. Explicitly-declared
        /// scenes never touch this list.
        inferred_manifests: std.ArrayListUnmanaged(asset_manifest_mod.InferredManifest) = .empty,

        /// Controls how `setScene` / `setSceneAtomic` react when
        /// `catalog.anyFailed(target.assets)` returns non-null during
        /// the manifest gate. `.fatal` (default) preserves today's
        /// behaviour — the swap is rolled back and the load error is
        /// returned. `.warn` logs via `game.log.warn` and proceeds
        /// (broken assets stay in `.failed` state; lookups return
        /// whatever fallback the loader installed). `.silent` proceeds
        /// without logging. Games that ship with optional assets
        /// (e.g. missing background music) can set this to `.warn`
        /// at startup.
        asset_failure_policy: AssetFailurePolicy = .fatal,

        /// Post-load render gate (#637). `loadGameState` resets the ECS
        /// and restores every saved entity *synchronously*, but the
        /// atlases those sprites reference get re-registered through the
        /// streaming catalog and re-decode/re-upload *asynchronously*
        /// over the next 1–2 seconds. During that window the
        /// re-registered atlases sit at `texture_id == 0` (the pending
        /// sentinel `registerPendingAtlas` writes), so `findSprite`
        /// returns 0 for them, `resolveAtlasSprites` stamps texture 0
        /// onto the restored sprites, and the draw path
        /// (`drawSpriteEntry`) — which has no entry for handle 0 —
        /// renders them with a bogus/last-bound backend texture. The
        /// visible result is the corruption flash the parent saw
        /// (workers briefly wearing the cloud atlas, or an unbound
        /// texture) until each atlas finishes re-binding via
        /// `markPendingLoaded`.
        ///
        /// This is the load-path counterpart to the scene-change
        /// readiness gate (`gateOnManifest` in `scene_mixin.zig`). When
        /// set, `render()` suppresses the world draw so no restored
        /// sprite is shown with an unbound atlas. It is cleared the
        /// first tick on which every gated atlas has re-bound (see
        /// `updatePostLoadRenderGate`). `null` means "no load gate
        /// active" (the common steady-state — zero cost per frame).
        ///
        /// Holds the loaded scene's declared `assets:` manifest slice
        /// (image entries are the ones we actually wait on; non-image
        /// entries are skipped by the readiness check). This borrows the
        /// program-lifetime slice off the `SceneEntry` — the same one
        /// `setScene`/`gateOnManifest` use — so it never needs freeing;
        /// scenes are registered once at startup and never unregistered
        /// at runtime. `null` means no gate is active.
        post_load_render_gate: ?[]const []const u8 = null,

        /// Hard deadline (frame number) at which the post-load render
        /// gate is force-cleared even if some atlas never reports bound.
        /// Belt-and-suspenders so a missing/renamed atlas, a failed
        /// decode under a `.warn`/`.silent` policy, or a backend that
        /// reuses handle 0 can NEVER wedge the world render permanently
        /// (a few frames of corruption is strictly better than a frozen
        /// black world). Set when the gate is armed; ignored while the
        /// gate is `null`.
        post_load_render_gate_deadline: u64 = 0,

        /// The image-atlas manifest the most recent `loadGameState`
        /// acquired (engine#638), so a SUBSEQUENT load can release it
        /// before acquiring the next one. Without this, loading save A
        /// then save B would acquire each manifest's atlases and never
        /// release A's — a slow refcount leak across repeated loads (and a
        /// double-pin when an in-game Load re-acquires the active scene's
        /// already-held manifest). The acquire/release is balanced here
        /// rather than via the scene-swap path because a load does NOT
        /// swap scenes (`current_scene_name` is unchanged), so
        /// `releasePreviousAssets` never sees it. Borrows the
        /// program-lifetime `SceneEntry.assets` slice; `null` when no load
        /// has pinned a manifest. Released in full on `deinit`.
        post_load_acquired_assets: ?[]const []const u8 = null,

        /// Whether the post-load gate's manifest has been bridged into
        /// `atlas_manager` yet (engine#638). The load path binds the whole
        /// manifest in ONE deterministic pass — the moment every atlas is
        /// `.ready` — mirroring the scene-change gate
        /// (`bridgeImageAssetsToAtlasManager`) instead of letting the
        /// per-tick incremental `bridgeAllReadyImageAssets` walk bind them
        /// one at a time as each upload lands. The all-at-once bind is the
        /// scene-change path's defining property and the reason it never
        /// exhibited the load path's intermittent mis-binding: a half-bound
        /// manifest is never observable. Reset to `false` when the gate
        /// arms; set `true` the frame the atomic bridge runs.
        post_load_render_gate_bridged: bool = false,

        // Active scene (type-erased) — managed by sceneLoaderFn / setActiveScene
        active_scene_ptr: ?*anyopaque = null,
        active_scene_update_fn: ?*const fn (*anyopaque, f32) void = null,
        active_scene_deinit_fn: ?*const fn (*anyopaque, std.mem.Allocator) void = null,
        active_scene_get_entity_fn: ?*const fn (*anyopaque, []const u8) ?Entity = null,
        active_scene_add_entity_fn: ?*const fn (*anyopaque, Entity) void = null,
        active_scene_clear_entities_fn: ?*const fn (*anyopaque) void = null,

        gizmo_reconcile_fn: ?*const fn (*Self) void = null,

        // Prefab spawning — set by JSONC scene bridge during loadScene.
        prefab_dir: ?[]const u8 = null,
        spawn_prefab_fn: ?*const fn (*Self, []const u8, Position) ?Entity = null,
        prefab_cache_ptr: ?*anyopaque = null,
        /// Live-instance transient refresh after a prefab hot-swap
        /// (#691) — set by the scene bridge next to `spawn_prefab_fn`
        /// because the refresh needs the BRIDGE's `Components`
        /// registry (which may differ from `ComponentRegistry`).
        /// Args: installed registry key + the retired generation as an
        /// opaque `*const jsonc.Value` (opaque for the same reason
        /// `prefab_cache_ptr` is — this file stays jsonc-free), null
        /// when the push inserted a brand-new prefab.
        refresh_prefab_fn: ?*const fn (*Self, []const u8, ?*const anyopaque) void = null,

        // Logging
        log: Log = .{},

        // Game state
        running: bool = true,
        /// Desired fullscreen state, owned by the engine. Scripts flip it
        /// via `setFullscreen`/`toggleFullscreen`; the generated frame
        /// loop drains `takeFullscreenRequest()` and applies the value to
        /// the window backend. The engine never imports a window module —
        /// same cooperative split as `running`/`isRunning`/`requestQuit`.
        fullscreen: bool = false,
        /// Set whenever `fullscreen` changes; cleared by the one-shot
        /// `takeFullscreenRequest()` drain so the backend toggle fires
        /// exactly once per change instead of every frame.
        fullscreen_dirty: bool = false,
        /// Desired vsync state, owned by the engine (same cooperative split
        /// as `fullscreen`). Scripts flip it via `setVsync`/`toggleVsync`;
        /// the generated frame loop drains `takeVsyncRequest()` and applies
        /// the value to the window backend (`window.setVsync`). Defaults ON
        /// to match every backend's prior hardcoded behaviour.
        vsync: bool = true,
        /// Set whenever `vsync` changes; cleared by the one-shot
        /// `takeVsyncRequest()` drain so the backend swap-interval change
        /// fires exactly once per change instead of every frame.
        vsync_dirty: bool = false,
        /// Opt-in: when true the engine advances every `SpriteAnimation`
        /// component itself each tick (on the time-scaled dt), so a game
        /// no longer needs a `sprite_animation_tick` script of its own.
        /// Off by default so existing projects that still drive animation
        /// from a script don't double-advance. Set via
        /// `setDriveSpriteAnimations`.
        drive_sprite_animations: bool = false,
        /// Freezes the engine-driven sprite-animation advance while set —
        /// the hook a pause menu toggles so sprite cycling stops without
        /// halting the rest of the script loop. Only meaningful alongside
        /// `drive_sprite_animations`. Set via `setSpriteAnimationsPaused`.
        sprite_animations_paused: bool = false,
        /// Opt-in: when true the engine steps every `Emitter`'s particle sim
        /// each tick and draws the live particles in the render pass (#750).
        /// Off by default so a game with no emitters is byte-identical; the
        /// scene loader flips it on automatically when it loads an `Emitter`
        /// (see `component_apply.applyEmitter`). Also settable via
        /// `setDriveParticles`. Gated on `scaled_dt != 0` in the tick, so a
        /// hard pause (`time_scale == 0`) freezes particles.
        drive_particles: bool = false,
        frame_number: u64 = 0,
        /// Current game state (e.g. "menu", "playing", "paused").
        /// Set via setState() or queueStateChange(). Default is "running".
        game_state: []const u8 = "running",
        pending_state_change: ?[]const u8 = null,
        state_change_count: usize = 0,
        /// Game-allocator-owned backing for `game_state` when the state
        /// name came from a runtime-parsed source whose backing storage
        /// has a shorter lifetime than the game (RFC #596 `meta.initial_state`
        /// reads through the loader's `parse_arena`, which is freed before
        /// the load returns; `editor_api.editor_set_state` hands in a
        /// studio-owned wasm buffer freed right after the call). When
        /// set, `game_state` aliases this slice. Freed on `deinit` and
        /// replaced (with the previous slice freed) on every
        /// `setStateOwned` call.
        owned_initial_state: ?[]u8 = null,
        /// Time scale factor: 0 = paused, 0.5 = slow-mo, 1.0 = normal, 2.0 = fast.
        /// When paused (0), rendering and GUI continue but tick logic stops.
        time_scale: f32 = 1.0,
        /// Plugin-accessible pause flag (#465). Plugin-shipped scripts
        /// (pathfinder's `Controller.advance`, asset-catalog's `pump`,
        /// etc.) gate on `game.isPaused()` instead of importing a
        /// game-side `GamePaused` component, which would cross the Zig
        /// module-path boundary. The game owns the source of truth —
        /// typically a tiny always-on script syncing its own
        /// `GamePaused` component into `setPaused` — and the engine
        /// just stores + dispatches the bool.
        paused: bool = false,

        /// Monotonic gameplay clock in seconds, accumulated from the
        /// *time-scaled* dt each `tick()` — so it freezes while paused
        /// (`time_scale == 0`) and slows under slow-mo. Read via
        /// `elapsedSeconds()`; flow `Cooldown`/`Delay` nodes (#25) time
        /// against it so gameplay timers don't advance on a pause menu.
        /// Distinct from `game_log.elapsed_s`, which stays wall-time for
        /// log stamps.
        clock_s: f64 = 0,

        // ── Fixed-timestep simulation phase (#751) ──────────────────────
        // Bevy-`FixedUpdate` equivalent: an accumulator-driven phase that
        // runs 0..N times per rendered frame at a stable dt, decoupled from
        // render rate, so physics / lockstep sim is deterministic across fps
        // caps. Fully additive — disabled by default, so a project with no
        // `fixed/` systems is byte-identical. Driven from `tick` via
        // `advanceFixedTimestep`; the machinery lives in
        // `game/fixed_timestep_mixin.zig`.

        /// Opt-in gate. While `false` (default) the fixed phase never runs
        /// (no accumulation, no `fixed_update` hooks, `fixed_alpha` stays 0).
        /// Flip via `setFixedTimestepEnabled`.
        fixed_timestep_enabled: bool = false,
        /// Fixed step length in seconds (default 1/60). Set via
        /// `setFixedTimestep`; the drain loop advances the sim in slices of
        /// exactly this size.
        fixed_dt: f64 = 1.0 / 60.0,
        /// Unconsumed (scaled) time carried between frames. Whole `fixed_dt`
        /// slices are drained out of it each active tick; the sub-step
        /// remainder becomes `fixed_alpha`. `f64` for stable long-session
        /// summation.
        fixed_accumulator: f64 = 0,
        /// Monotonic count of fixed steps run since game start (never reset).
        /// Read via `fixedStepCount()` — the lockstep / state-hash cursor.
        fixed_step_count: u64 = 0,
        /// Render-interpolation factor in `[0, 1)`: `fixed_accumulator /
        /// fixed_dt` after the last drain. Read via `fixedAlpha()` to lerp
        /// visual state between the previous and current fixed states.
        fixed_alpha: f32 = 0,
        /// Spiral-of-death clamp: the most fixed steps a single frame may
        /// run before the remaining backlog is dropped (the sim slows rather
        /// than freezing on an unbounded catch-up after a hitch). At the 1/60
        /// default this caps a frame at ~83 ms of sim before it gives up.
        max_fixed_steps_per_frame: u32 = 5,

        /// Runtime timer wheel (#25 Stage 2). Owns its pending list on the
        /// game allocator; initialized in `init`, drained in `deinit`. Flow
        /// `Delay` codegen emits `game.scheduler.after(seconds, entity, ctx,
        /// func)`. Ticked from `tick()` against `elapsedSeconds()`, so timers
        /// inherit pause + slow-mo for free. `undefined` until `init` wires
        /// the type-erased game pointer + clock/liveness trampolines.
        scheduler: SchedulerType = undefined,

        /// Player↔controller mapping layer (#611). `void` (zero-size,
        /// elided) unless the project's `GameEvents` carries a player-level
        /// controller variant — then it's a `DefaultControllerManager` the
        /// engine feeds drained gamepad events and drains player-level
        /// events out of, each tick (see `scanInputEvents` / `tick`). The
        /// game reaches the assignment API via `game.controllerManager()`.
        controller_manager: ControllerManagerType = if (controller_events_wanted)
            ControllerManagerType.init(.{})
        else {},

        /// Opt-in: when `true`, an active player losing its controller (a
        /// real `player_controller_lost`, past the debounce window) drives
        /// `setPaused(true)` so plugin-gated work (`Controller.advance`,
        /// #465) halts and the game can raise a "reconnect Player N"
        /// prompt. Cleared back to running when every player is whole again
        /// (a `player_controller_restored` leaves nobody waiting). OFF by
        /// default — the engine never forces a pause. Toggle with
        /// `setAutoPauseOnControllerLost`.
        auto_pause_on_controller_lost: bool = false,

        /// Connect-out preview channel to the labelle-gui editor
        /// (`--preview-mode <host:port>`). `null` in normal runs — the
        /// generated `main.zig` constructs a `Preview` and assigns it
        /// here when the flag is present. Lifetime: owned by `Game`
        /// when set, but `Preview.deinit` is the caller's
        /// responsibility (mirrors the spawn-side pattern in
        /// `preview_mode.zig`'s doc — the assembler-generated main
        /// calls `sendBye` + `deinit` on shutdown).
        ///
        /// When set, ECS lifecycle paths (`createEntity`,
        /// `destroyEntity`, `addComponent`, `setComponent`,
        /// `setPosition`) emit Phase 2 telemetry frames. Component
        /// frames are gated by `Preview.isComponentSubscribed` so an
        /// idle editor pays nothing per write.
        preview: ?preview_mode_mod.Preview = null,

        // Profiling (debug builds only)
        /// Opaque pointer to ScriptRunner's profile array. Set by generated code.
        script_profile_ptr: ?*const anyopaque = null,
        script_profile_count: usize = 0,
        /// Opaque pointer to SystemRegistry's plugin_profile array. Set by generated code.
        plugin_profile_ptr: ?*const anyopaque = null,
        plugin_profile_count: usize = 0,

        /// FPS / frame-time tracker for the debug inspector (#380). Fed one
        /// `dt` per `tick` (see `loop_mixin`). Ungated — the per-frame cost
        /// is a single ring write + EMA update — so the inspector's FPS
        /// header always works even without `LABELLE_PROFILE`.
        frame_profiler: frame_profiler_mod.FrameProfiler = .{},

        // Hot reload
        hot_reload_dirty: bool = false,

        // ── Roster cache state (#653) ─────────────────────────────
        /// Monotonic epoch bumped on every structural mutation. Read
        /// slots compare their stored `gen` against this to detect
        /// staleness. Wraps with `+%=`; collisions across a full u64
        /// wrap are not a practical concern.
        roster_generation: u64 = 0,
        /// Cached `entitiesWith` rosters, keyed by the comptime tag-set
        /// hash (`rosterKey`). Never evicts — the key space is
        /// statically bounded by the compiled game's tag-sets — so a
        /// borrowed slice is never clobbered by a read of another
        /// tag-set (#657). See `RosterSlot`.
        roster_cache: std.AutoHashMap(u64, RosterSlot) = undefined,

        // Gizmos
        gizmos_enabled: bool = true,
        gizmo_state: gizmo_draws_mod.GizmoState(Entity),

        // In-game UI kit (issue #771). Per-frame draw commands submitted by
        // game code (`submitUiDrawList`), drained + drawn in `render()` after
        // the world pass and before gizmos; baked fonts retained across
        // frames for the renderer's text pass + the kit's FontResolver.
        ui_draw_list: std.ArrayListUnmanaged(ui_draw_list_mod.UiDrawCmd) = .empty,
        ui_render_opts: ui_draw_list_mod.UiRenderOptions = .{},
        ui_fonts: ui_draw_list_mod.UiFontStore = .empty,

        // Debug-only: tombstone ring buffer (#420)
        tombstones: if (is_debug) [tombstone_size]?TombstoneEntry else void =
            if (is_debug) [_]?TombstoneEntry{null} ** tombstone_size else {},
        tombstone_cursor: if (is_debug) usize else void =
            if (is_debug) 0 else {},

        // ── Construction + scheduler glue — `game/game_init.zig` ──
        // (`deinit` stays with the lifecycle mixin, which owns the
        // shutdown ordering contract.)
        pub const init = InitMixin.init;
        pub const bindScheduler = InitMixin.bindScheduler;

        pub const deinit = LifecycleMixin.deinit;

        pub const setHooks = LifecycleMixin.setHooks;

        pub const emitHook = EventsMixin.emitHook;

        /// Emit a game event. Buffered and delivered to scripts at end of frame.
        pub const emit = EventsMixin.emit;

        /// Engine-side tolerant emit for the `engine__<event>` variants
        /// declared on `engine.Events` (RFC-FLOW-VOCABULARY phase 6,
        /// #578). The assembler folds the engine's `Events` block into
        /// `PluginEvents`, which is itself merged into `GameEvents`. So
        /// in any project where the assembler ran, `GameEvents` has the
        /// `engine__<event>` variants. But unit tests build `Game`
        /// directly with `GameEvents = void` (the `GameWith(Hooks)`
        /// path), so the engine's own lifecycle code can't blindly call
        /// `self.emit(.{ .engine__game_init = .{} })` — there would be
        /// no such field in the union.
        ///
        /// This helper does the comptime gate: when `GameEvents` is a
        /// union *and* declares the variant tag, the dispatch goes
        /// through `emit`; otherwise the call folds away to a no-op.
        ///
        /// The variant must be passed as `comptime`-known struct
        /// literal — e.g. `self.emitEngineEvent("engine__game_init", .{})`
        /// — so the field-presence check resolves at compile time. The
        /// payload type is inferred against
        /// `@FieldType(GameEvents, tag)`, mirroring how
        /// `dispatchEvents` reconstructs the union variant.
        pub const emitEngineEvent = EventsMixin.emitEngineEvent;
        /// Synchronous variant of `emitEngineEvent` — dispatches in-phase
        /// instead of buffering. Used by the fixed-timestep phase so
        /// flow-driven fixed systems run in the fixed slice, not a phase
        /// late. Full docs in `game/events_mixin.zig`.
        pub const emitEngineEventSync = EventsMixin.emitEngineEventSync;

        /// Emit a game event synchronously — dispatch to registered hooks
        /// immediately, bypassing the end-of-frame buffer. Use when the
        /// caller needs the handler to have run before the next
        /// statement (cross-plugin state machines that can't tolerate
        /// the buffered-dispatch window).
        ///
        /// ## Caveats
        ///
        /// The event-buffer design in the custom-game-events RFC exists
        /// precisely to avoid these, so reach for `emitSync` only when
        /// the buffered path is provably wrong for the call site:
        ///
        /// - **Re-entrancy.** Handlers run mid-tick, inside whatever
        ///   script or plugin called `emitSync`. A handler that itself
        ///   mutates entity state, emits more events, or calls back
        ///   into the caller's own code can interleave with partially-
        ///   completed work on the stack above. Favour buffered `emit`
        ///   unless the caller is a leaf operation.
        ///
        /// - **Ordering vs buffered events.** `emitSync` does NOT drain
        ///   the end-of-frame buffer first. A hook fired synchronously
        ///   mid-tick runs *before* all the events `emit` queued
        ///   earlier in the same frame, even though those were queued
        ///   first. Mixing the two on a single event kind produces
        ///   out-of-order handler calls — usually not what you want.
        pub const emitSync = EventsMixin.emitSync;

        /// Deliver buffered game events to hooks. Called at end of frame.
        pub const dispatchEvents = EventsMixin.dispatchEvents;

        /// Route a studio-issued play-time plugin editor command (the
        /// `editor_plugin_command` bridge export, editor-contract v1.7) to its
        /// declared handler. See `game/editor_command_mixin.zig`.
        pub const editorPluginCommand = EditorCommandMixin.editorPluginCommand;

        /// Response-aware plugin-command dispatch (#758): same routing, plus
        /// the caller receives the (at most one) response a handler wrote via
        /// `engine.plugin_command.respond` during the synchronous dispatch.
        /// Backs the `editor_plugin_command_out` bridge export (v1.8) and the
        /// script contract's `labelle_plugin_call` out-buffer (v1.2). See
        /// `game/editor_command_mixin.zig` for the channel's semantics
        /// (first-writer-wins, bounded, empty-folds-to-dispatched).
        pub const editorPluginCommandOut = EditorCommandMixin.editorPluginCommandOut;

        // ── Debug entity guards (#419, #420) ─────────────────────

        pub const recordTombstone = EntityMixin.recordTombstone;

        pub const findTombstone = EntityMixin.findTombstone;
        pub const assertEntityAlive = EntityMixin.assertEntityAlive;

        // ── Entity Management ─────────────────────────────────────
        pub const createEntity = EntityMixin.createEntity;
        pub const spawnPrefab = EntityMixin.spawnPrefab;
        pub const spawnFromPrefab = EntityMixin.spawnFromPrefab;
        pub const tagAsPrefabInstance = EntityMixin.tagAsPrefabInstance;
        pub const destroyEntity = EntityMixin.destroyEntity;
        pub const destroyEntityOnly = EntityMixin.destroyEntityOnly;

        // ── View collection helpers (#510) ────────────────────────
        pub const collectEntities = EntityMixin.collectEntities;
        pub const collectEntitiesBuf = EntityMixin.collectEntitiesBuf;
        pub const collectEntitiesIf = EntityMixin.collectEntitiesIf;
        pub const collectEntitiesBufIf = EntityMixin.collectEntitiesBufIf;

        // ── Visuals (mixin) ──────────────────────────────────────
        pub const addSprite = Visuals.addSprite;
        pub const addShape = Visuals.addShape;
        pub const addText = Visuals.addText;
        pub const addIcon = Visuals.addIcon;
        pub const addGizmo = Visuals.addGizmo;
        pub const removeSprite = Visuals.removeSprite;
        pub const removeShape = Visuals.removeShape;
        pub const removeText = Visuals.removeText;
        pub const setZIndex = Visuals.setZIndex;
        pub const setSpriteFlip = Visuals.setSpriteFlip;
        pub const setMaterial = Visuals.setMaterial;
        pub const clearMaterial = Visuals.clearMaterial;

        // ── Tilemap (mixin, T2 Phase 2) ──────────────────────────
        pub const addTilemap = TilemapMixin.addTilemap;
        pub const acquireTilemap = TilemapMixin.acquireTilemap;
        pub const releaseTilemap = TilemapMixin.releaseTilemap;
        pub const removeTilemap = TilemapMixin.removeTilemap;
        pub const renderTilemaps = TilemapMixin.renderTilemaps;
        pub const tilemapRuntime = TilemapMixin.tilemapRuntime;
        pub const addEmbeddedTilemapAsset = TilemapMixin.addEmbeddedTilemapAsset;
        pub const clearTilemaps = TilemapMixin.clearTilemaps;
        pub const deinitTilemaps = TilemapMixin.deinitTilemaps;

        // ── Particles / Emitter side-table (#750) — `game/emitter_mixin.zig`
        pub const setDriveParticles = EmitterMixin.setDriveParticles;
        pub const particleSystem = EmitterMixin.particleSystem;
        pub const acquireParticleSystem = EmitterMixin.acquireParticleSystem;
        pub const releaseParticleSystem = EmitterMixin.releaseParticleSystem;
        pub const clearParticleSystems = EmitterMixin.clearParticleSystems;
        pub const reapGhostEmitters = EmitterMixin.reapGhostEmitters;
        pub const deinitParticleSystems = EmitterMixin.deinitParticleSystems;

        // ── Roster cache (#653, #657) — `game/roster.zig` ─────────
        // Borrowed-slice lifetime contract + design rationale live in
        // the module header there.
        pub const entitiesWith = RosterMixin.entitiesWith;
        pub const bumpRoster = RosterMixin.bumpRoster;

        // ── Position & Hierarchy ──────────────────────────────────

        pub const setPosition = ComponentsMixin.setPosition;
        pub const getPosition = ComponentsMixin.getPosition;
        pub const getWorldPosition = ComponentsMixin.getWorldPosition;
        pub const setWorldPosition = ComponentsMixin.setWorldPosition;
        pub const setParent = ComponentsMixin.setParent;
        pub const setParentKeepTransform = ComponentsMixin.setParentKeepTransform;
        pub const removeParent = ComponentsMixin.removeParent;
        pub const removeParentKeepTransform = ComponentsMixin.removeParentKeepTransform;
        pub const detachFromParent = ComponentsMixin.detachFromParent;
        pub const getParent = ComponentsMixin.getParent;
        pub const getChildren = ComponentsMixin.getChildren;
        pub const hasChildren = ComponentsMixin.hasChildren;
        pub const isRoot = ComponentsMixin.isRoot;

        // ── Generic Component Access ──────────────────────────────
        pub const addComponent = ComponentsMixin.addComponent;
        pub const setComponent = ComponentsMixin.setComponent;
        pub const getComponent = ComponentsMixin.getComponent;
        pub const setField = ComponentsMixin.setField;
        pub const hasComponent = ComponentsMixin.hasComponent;
        pub const removeComponent = ComponentsMixin.removeComponent;
        pub const fireOnReady = ComponentsMixin.fireOnReady;

        // ── Input (mixin) ────────────────────────────────────────
        pub const isKeyDown = InputMixin.isKeyDown;
        pub const isKeyPressed = InputMixin.isKeyPressed;
        pub const isKeyReleased = InputMixin.isKeyReleased;
        pub const getMouseX = InputMixin.getMouseX;
        pub const getMouseY = InputMixin.getMouseY;
        pub const getMouse = InputMixin.getMouse;
        pub const getMouseWheelMove = InputMixin.getMouseWheelMove;
        pub const isMouseButtonDown = InputMixin.isMouseButtonDown;
        pub const isMouseButtonPressed = InputMixin.isMouseButtonPressed;
        pub const isMouseButtonReleased = InputMixin.isMouseButtonReleased;
        pub const isGamepadAvailable = InputMixin.isGamepadAvailable;
        pub const isGamepadButtonDown = InputMixin.isGamepadButtonDown;
        pub const isGamepadButtonPressed = InputMixin.isGamepadButtonPressed;
        pub const getGamepadAxisValue = InputMixin.getGamepadAxisValue;
        pub const getTouchCount = InputMixin.getTouchCount;
        pub const getTouchX = InputMixin.getTouchX;
        pub const getTouchY = InputMixin.getTouchY;
        pub const getTouchId = InputMixin.getTouchId;

        /// Convert a physical-pixel screen coordinate (raw touch / mouse
        /// event coords from the backend) to a design-pixel coordinate
        /// inside the pillarboxed/letterboxed canvas. Use this before
        /// feeding touch / mouse coords to `cam.screenToWorld` so the
        /// math lines up with the game's design coordinate system.
        ///
        /// Backends without a design/physical distinction (raylib) get
        /// a passthrough — the input is returned unchanged.
        pub const screenToDesign = MiscMixin.screenToDesign;

        /// Convert a physical-pixel screen coordinate into the project's
        /// **logical** coordinate space — the same space as `Position` and
        /// `setPosition`. This first maps through `screenToDesign` (raw,
        /// y-down design pixels, unchanged) and then applies the project's
        /// `.y_axis` convention to the Y component via core's canonical
        /// `screenToLogicalY` transform.
        ///
        /// Under `.up` (today's default behavior) this flips Y
        /// (`logical_y = height - design_y`) so a click at the top of the
        /// window yields a *large* logical `y` — matching where an entity
        /// placed there needs to sit. Under `.down` it's the identity, so
        /// `screenToLogical` == `screenToDesign`.
        ///
        /// Use this for axis-aware picking / drag-to-place / gizmo
        /// hit-testing (RFC Q1→(b), Q3). Code that wants raw window-space
        /// coordinates (e.g. forwarding to imgui, or `cam.screenToWorld`,
        /// which applies its own flip) keeps using `screenToDesign`.
        pub const screenToLogical = MiscMixin.screenToLogical;

        /// The project's logical Y-axis convention as a runtime value. Mirrors
        /// the comptime `Game.y_axis` constant for callers that prefer an
        /// accessor (RFC §3).
        pub const yAxis = MiscMixin.yAxis;

        // ── Audio (mixin) ────────────────────────────────────────
        pub const playSound = AudioMixin.playSound;
        pub const stopSound = AudioMixin.stopSound;
        pub const setVolume = AudioMixin.setVolume;
        pub const videoSupported = VideoMixin.videoSupported;
        pub const openVideo = VideoMixin.openVideo;
        pub const updateVideo = VideoMixin.updateVideo;
        pub const drawVideo = VideoMixin.drawVideo;
        pub const videoPlaying = VideoMixin.videoPlaying;
        pub const closeVideo = VideoMixin.closeVideo;
        pub const addVideo = VideoMixin.addVideo;
        pub const removeVideo = VideoMixin.removeVideo;
        pub const renderVideos = VideoMixin.renderVideos;

        // ── GUI (mixin) ──────────────────────────────────────────
        pub const guiBegin = GuiMixin.guiBegin;
        pub const guiEnd = GuiMixin.guiEnd;
        pub const guiWantsMouse = GuiMixin.guiWantsMouse;
        pub const guiWantsKeyboard = GuiMixin.guiWantsKeyboard;
        pub const renderAllViews = GuiMixin.renderAllViews;
        pub const renderView = GuiMixin.renderView;

        // ── Gizmos (mixin) ───────────────────────────────────────
        pub const setGizmosEnabled = GizmoMixin.setGizmosEnabled;
        pub const isGizmosEnabled = GizmoMixin.isGizmosEnabled;
        pub const drawGizmoLine = GizmoMixin.drawGizmoLine;
        pub const drawGizmoRect = GizmoMixin.drawGizmoRect;
        pub const drawGizmoCircle = GizmoMixin.drawGizmoCircle;
        pub const drawGizmoArrow = GizmoMixin.drawGizmoArrow;
        pub const drawGizmoLineCategory = GizmoMixin.drawGizmoLineCategory;
        pub const drawGizmoRectCategory = GizmoMixin.drawGizmoRectCategory;
        pub const drawGizmoCircleCategory = GizmoMixin.drawGizmoCircleCategory;
        pub const drawGizmoArrowCategory = GizmoMixin.drawGizmoArrowCategory;
        pub const setGizmoCategory = GizmoMixin.setGizmoCategory;
        pub const isGizmoCategoryEnabled = GizmoMixin.isGizmoCategoryEnabled;
        pub const drawGizmoLineScreen = GizmoMixin.drawGizmoLineScreen;
        pub const drawGizmoRectScreen = GizmoMixin.drawGizmoRectScreen;
        pub const drawGizmoCircleScreen = GizmoMixin.drawGizmoCircleScreen;
        pub const drawGizmoArrowScreen = GizmoMixin.drawGizmoArrowScreen;
        pub const clearGizmos = GizmoMixin.clearGizmos;
        pub const clearGizmoGroup = GizmoMixin.clearGizmoGroup;
        pub const getGizmoDraws = GizmoMixin.getGizmoDraws;
        pub const selectEntity = GizmoMixin.selectEntity;
        pub const deselectEntity = GizmoMixin.deselectEntity;
        pub const isEntitySelected = GizmoMixin.isEntitySelected;
        pub const clearSelection = GizmoMixin.clearSelection;
        pub const renderGizmos = GizmoMixin.renderGizmos;

        // ── Render-phase custom meshes (mixin) ───────────────────
        /// Immediate textured-mesh submission for the render phase — the seam
        /// `labelle-spine` submits skinned meshes through (labelle-gfx#290
        /// Stage 4). Forwards to the renderer's optional `drawMesh`; a no-op
        /// on renderers/backends that don't declare it. Plugins call this from
        /// a `Systems.renderMeshes(game)` callback (see `SystemRegistry`).
        pub const drawMesh = MeshMixin.drawMesh;

        // ── In-game UI kit (issue #771) ──
        pub const submitUiDrawList = UiKitMixin.submitUiDrawList;
        pub const renderSubmittedUi = UiKitMixin.renderSubmittedUi;
        pub const clearSubmittedUi = UiKitMixin.clearSubmittedUi;
        pub const bakeUiFont = UiKitMixin.bakeUiFont;
        pub const uiFont = UiKitMixin.uiFont;
        pub const resolveUiFrame = UiKitMixin.resolveUiFrame;
        pub const reuploadUiFonts = UiKitMixin.reuploadUiFonts;

        // ── Offscreen render targets / transport mirror (mixin) ──
        /// Render a scene into a texture instead of the screen, then draw that
        /// texture elsewhere (the "transport mirror") — same primitive as headless
        /// capture (labelle-bgfx#36). Opaque `u32` handles. Each forwards to the
        /// renderer's optional render-target op; a no-op / INVALID on renderers or
        /// backends that don't declare it (bgfx today; raylib/sokol/… omit it).
        pub const createRenderTarget = RenderTargetMixin.createRenderTarget;
        pub const beginRenderTarget = RenderTargetMixin.beginRenderTarget;
        pub const endRenderTarget = RenderTargetMixin.endRenderTarget;
        pub const drawRenderTarget = RenderTargetMixin.drawRenderTarget;
        pub const destroyRenderTarget = RenderTargetMixin.destroyRenderTarget;

        // ── Post-fx stack passthrough (labelle-gfx#305 Phase 2 Slice C, mixin) ──
        /// Seed / mutate the full-screen post-fx stack at runtime — forwards to
        /// the internal gfx retained engine's `PostFxDriver`. The same stack the
        /// `project.labelle` `.post_fx` seed feeds. No-op on renderers/backends
        /// without post-fx support (older gfx, StubRender, test mocks).
        pub const setPostFx = PostFxMixin.setPostFx;
        pub const pushPostPass = PostFxMixin.pushPostPass;
        pub const clearPostFx = PostFxMixin.clearPostFx;

        // ── Scene Management (mixin) ─────────────────────────────
        pub const registerScene = SceneMixin.registerScene;
        pub const registerSceneSimple = SceneMixin.registerSceneSimple;
        pub const registerSceneWithAssets = SceneMixin.registerSceneWithAssets;

        /// Register an embedded JSONC scene source so `"include"`
        /// directives can resolve against memory instead of disk.
        /// Mirrors `addEmbeddedPrefab` — the assembler emits one call
        /// per scene fragment in `main()` / `init()` so WASM and
        /// Android builds (no project directory in cwd) can still
        /// resolve nested scene includes. `path` is the include-
        /// relative path (e.g. `"scenes/obstacles.jsonc"`); `source`
        /// is typically a comptime `@embedFile(...)` slice. Caller
        /// retains no ownership — the map dupes the key and borrows
        /// the source's program-lifetime slice.
        pub const addEmbeddedSceneSource = MiscMixin.addEmbeddedSceneSource;

        /// Runtime scene-source override map (labelle-studio Play mode /
        /// `editor_api`) — see `game/misc_mixin.zig` for the ownership
        /// and lookup rules.
        pub const setSceneSourceOverride = MiscMixin.setSceneSourceOverride;
        pub const removeSceneSourceOverride = MiscMixin.removeSceneSourceOverride;
        pub const sceneSourceOverride = MiscMixin.sceneSourceOverride;

        /// Runtime animation-def overrides (labelle-studio Play mode /
        /// `editor_api.editor_load_animation_def`) — see
        /// `game/animation_runtime_mixin.zig` for the `anim_def_name`
        /// refresh convention and the fallback contract.
        pub const loadAnimationDefSource = AnimationRuntimeMixin.loadAnimationDefSource;
        pub const runtimeAnimDef = AnimationRuntimeMixin.runtimeAnimDef;
        pub const refreshAnimationStates = AnimationRuntimeMixin.refreshAnimationStates;

        /// Runtime prefab-definition hot-swap (labelle-studio Play mode /
        /// `editor_api.editor_reload_prefab`) — replace-or-insert the
        /// prefab registry entry so FUTURE spawns use the new source;
        /// existing instances keep their data. See
        /// `game/prefab_runtime_mixin.zig` for the scope contract.
        pub const reloadPrefabSource = PrefabRuntimeMixin.reloadPrefabSource;
        pub const setSceneAssets = SceneMixin.setSceneAssets;
        pub const setSceneSource = SceneMixin.setSceneSource;
        pub const setSceneInitialState = SceneMixin.setSceneInitialState;
        pub const setScene = SceneMixin.setScene;
        pub const setSceneAtomic = SceneMixin.setSceneAtomic;
        pub const queueSceneChange = SceneMixin.queueSceneChange;
        pub const queueSceneChangeAtomic = SceneMixin.queueSceneChangeAtomic;
        pub const getCurrentSceneName = SceneMixin.getCurrentSceneName;
        pub const pendingSceneName = SceneMixin.pendingSceneName;
        pub const bridgeAllReadyImageAssets = SceneMixin.bridgeAllReadyImageAssets;
        pub const bridgeManifest = SceneMixin.bridgeManifest;

        /// Register a runtime JSONC scene by name.
        /// The scene file is loaded from disk when setScene() is called.
        pub const registerJsoncScene = MiscMixin.registerJsoncScene;

        // ── Hot Reload ──────────────────────────────────────────────

        /// Signal that the current scene should be reloaded on the next tick.
        pub const requestReload = MiscMixin.requestReload;

        // ── Save/Load (mixin) ───────────────────────────────────────
        pub const saveGameState = SaveLoadMixin.saveGameState;
        pub const loadGameState = SaveLoadMixin.loadGameState;
        pub const armPostLoadRenderGate = SaveLoadMixin.armPostLoadRenderGate;
        pub const updatePostLoadRenderGate = SaveLoadMixin.updatePostLoadRenderGate;
        pub const releaseLoadAcquired = SaveLoadMixin.releaseLoadAcquired;

        // ── Fixed-timestep phase (mixin, #751) ──────────────────────
        // Full docs in `game/fixed_timestep_mixin.zig`.
        pub const setFixedTimestepEnabled = FixedTimestepMixin.setFixedTimestepEnabled;
        pub const isFixedTimestepEnabled = FixedTimestepMixin.isFixedTimestepEnabled;
        pub const setFixedTimestep = FixedTimestepMixin.setFixedTimestep;
        pub const fixedTimestep = FixedTimestepMixin.fixedTimestep;
        pub const fixedAlpha = FixedTimestepMixin.fixedAlpha;
        pub const fixedStepCount = FixedTimestepMixin.fixedStepCount;
        pub const advanceFixedTimestep = FixedTimestepMixin.advanceFixedTimestep;

        // ── Game State Machine (mixin) ──────────────────────────────
        pub const setState = StateMixin.setState;
        pub const setStateOwned = StateMixin.setStateOwned;
        pub const queueStateChange = StateMixin.queueStateChange;
        pub const getState = StateMixin.getState;

        // ── Pause flag (#465) ───────────────────────────────────────
        // Full docs in `game/scene_runtime_mixin.zig`.
        pub const setPaused = SceneRuntimeMixin.setPaused;
        pub const isPaused = SceneRuntimeMixin.isPaused;

        // ── ControllerManager game-facing API (#611) ─────────────────
        // Thin forwarders over the embedded `controller_manager`; available
        // only when `GameEvents` carries a player-level controller variant
        // (else the field is `void` and these `@compileError`). Full docs
        // in `game/input_events_mixin.zig`.
        pub const controllerManager = InputEventsMixin.controllerManager;
        pub const assignController = InputEventsMixin.assignController;
        pub const unassignPlayer = InputEventsMixin.unassignPlayer;
        pub const playerForController = InputEventsMixin.playerForController;
        pub const controllerForPlayer = InputEventsMixin.controllerForPlayer;
        pub const setAutoPauseOnControllerLost = InputEventsMixin.setAutoPauseOnControllerLost;

        // ── Active scene runtime (mixin) ──────────────────────────
        // Full docs in `game/scene_runtime_mixin.zig` /
        // `game/entity_mixin.zig` (scene-entity tracking).
        pub const unloadCurrentScene = SceneRuntimeMixin.unloadCurrentScene;
        pub const trackSceneEntity = EntityMixin.trackSceneEntity;
        pub const untrackSceneEntity = EntityMixin.untrackSceneEntity;
        pub const setActiveScene = SceneRuntimeMixin.setActiveScene;
        pub const getEntityByName = SceneRuntimeMixin.getEntityByName;
        pub const addEntityToActiveScene = SceneRuntimeMixin.addEntityToActiveScene;
        pub const clearActiveSceneEntities = SceneRuntimeMixin.clearActiveSceneEntities;

        /// Destroy all entities and visuals atomically, then reinitialize
        /// the ECS backend and renderer to a clean state. The nested entity
        /// arena is also reset. Scene tracking (active_scene_ptr, etc.) is
        /// NOT affected — the scene remains active with an empty entity list.
        /// Call clearActiveSceneEntities() first if the scene's entity list
        /// should also be cleared.
        // ── World Management ─────────────────────────────────────

        pub const createWorld = WorldMixin.createWorld;
        pub const destroyWorld = WorldMixin.destroyWorld;
        pub const setActiveWorld = WorldMixin.setActiveWorld;
        pub const renameWorld = WorldMixin.renameWorld;
        pub const getWorld = WorldMixin.getWorld;
        pub const getActiveWorldName = WorldMixin.getActiveWorldName;
        pub const worldExists = WorldMixin.worldExists;
        pub const resetEcsBackend = WorldMixin.resetEcsBackend;
        pub const teardownActiveScene = WorldMixin.teardownActiveScene;

        // ── Game Loop / Fullscreen / sprite-anim / time scale ─────
        // Runtime-control accessors; full docs in
        // `game/lifecycle_mixin.zig`. The engine owns the *desired*
        // fullscreen flag — the generated `main.zig` drains
        // `takeFullscreenRequest()` and forwards it to the window backend,
        // keeping the library backend-agnostic.
        pub const quit = LifecycleMixin.quit;
        pub const isRunning = LifecycleMixin.isRunning;
        pub const setFullscreen = LifecycleMixin.setFullscreen;
        pub const toggleFullscreen = LifecycleMixin.toggleFullscreen;
        pub const isFullscreen = LifecycleMixin.isFullscreen;
        pub const takeFullscreenRequest = LifecycleMixin.takeFullscreenRequest;
        pub const setVsync = LifecycleMixin.setVsync;
        pub const toggleVsync = LifecycleMixin.toggleVsync;
        pub const isVsync = LifecycleMixin.isVsync;
        pub const takeVsyncRequest = LifecycleMixin.takeVsyncRequest;
        pub const setDriveSpriteAnimations = LifecycleMixin.setDriveSpriteAnimations;
        pub const setSpriteAnimationsPaused = LifecycleMixin.setSpriteAnimationsPaused;
        pub const spriteAnimationsPaused = LifecycleMixin.spriteAnimationsPaused;
        pub const setTimeScale = LifecycleMixin.setTimeScale;
        pub const getTimeScale = LifecycleMixin.getTimeScale;
        pub const pause = LifecycleMixin.pause;
        pub const resume_ = LifecycleMixin.resume_;
        // GPU surface lifecycle (Android context loss, epic #386 Phase 4).
        // The bgfx-Android backend calls these on TERM_WINDOW /
        // INIT_WINDOW to invalidate + re-upload GPU-resident assets.
        pub const surfaceLost = LifecycleMixin.surfaceLost;
        pub const surfaceRestored = LifecycleMixin.surfaceRestored;
        pub const elapsedSeconds = LifecycleMixin.elapsedSeconds;

        // ── Input events (labelle-gui#208) ───────────────────────
        //
        // Comptime gates mirroring `emitEngineEvent`'s `@hasField`
        // check, grouped per input category. When the project's
        // `GameEvents` doesn't carry a category's variants, the whole
        // scan loop for that category folds away — an unused game pays
        // NOTHING per frame (no enum iteration, no backend polling).

        /// True when `GameEvents` declares `field` (the qualified
        /// `engine__<name>` tag). Same gate `emitEngineEvent` uses.
        pub inline fn engineEventWanted(comptime field: []const u8) bool {
            if (!has_events) return false;
            if (@typeInfo(GameEvents) != .@"union") return false;
            return @hasField(GameEvents, field);
        }

        pub const keyboard_events_wanted = engineEventWanted("engine__key_pressed") or
            engineEventWanted("engine__key_released");
        pub const mouse_events_wanted = engineEventWanted("engine__mouse_button_pressed") or
            engineEventWanted("engine__mouse_button_released");
        pub const gamepad_events_wanted = engineEventWanted("engine__gamepad_connected") or
            engineEventWanted("engine__gamepad_disconnected") or
            // The ControllerManager consumes the SAME drained gamepad
            // events, so any project that listens to a player-level event
            // forces the drain on too — even if it never listens to the raw
            // `gamepad_*` pair (#611).
            controller_events_wanted;

        /// True when the project's `GameEvents` carries any
        /// `ControllerManager` player-level variant. Gates the manager's
        /// state machine + output drain so an unused game pays nothing
        /// (the whole `controller_manager` field + per-tick work folds
        /// away). Mirrors the `gamepad_events_wanted` gate.
        pub const controller_events_wanted = engineEventWanted("engine__controller_available") or
            engineEventWanted("engine__controller_removed") or
            engineEventWanted("engine__player_joined") or
            engineEventWanted("engine__player_controller_lost") or
            engineEventWanted("engine__player_controller_restored");

        /// The concrete `ControllerManager` type for this game (toolkit
        /// default capacities). `void` when no controller event is wanted —
        /// the field then has zero size and all wiring folds away.
        pub const ControllerManagerType = if (controller_events_wanted)
            controller_manager_mod.DefaultControllerManager
        else
            void;

        // Input-event scanning + ControllerManager drain live in
        // `InputEventsMixin`; `tick` calls them as `InputEventsMixin.scan*`.

        pub const tick = LoopMixin.tick;

        pub const render = LoopMixin.render;

        // ── Camera ────────────────────────────────────────────────

        const has_camera = @hasDecl(RenderImpl, "CameraType");
        pub const CameraType = if (has_camera) RenderImpl.CameraType else void;
        pub const CameraManagerType = if (has_camera) RenderImpl.CameraManagerType else void;

        /// Set the screen height on the active world's renderer.
        pub const setScreenHeight = MiscMixin.setScreenHeight;

        /// Get the primary camera (for renderers that support cameras).
        pub const getCamera = if (has_camera) MiscMixin.getCameraImpl else void;

        /// Get the camera manager (for multi-camera / split-screen).
        pub const getCameraManager = if (has_camera) MiscMixin.getCameraManagerImpl else void;

        /// Resolve a camera by tag (camera-bound layers, #723/#724). Returns
        /// the lowest active slot carrying `tag`, or `null`. Comptime no-op
        /// returning `null` on renderers without a settable camera OR without
        /// the tagged (gfx ≥1.26) camera manager — the same gate the tagged
        /// seeding uses, so a non-tagged manager never reaches `findByTag`.
        pub const getCameraByTag = if (has_camera and camera_mod.hasTaggedCameraManager(@This())) MiscMixin.getCameraByTagImpl else struct {
            fn f(_: *Self, _: []const u8) ?*CameraType {
                return null;
            }
        }.f;

        // ── Camera component seed / sync (#714) ───────────────────
        /// Seed `getCamera()` from the authored `Camera` component (world
        /// position + zoom). Called once after scene instantiation and every
        /// paused frame from `editor_api.frame`. Comptime no-op on renderers
        /// without a settable camera. See `game/camera_mixin.zig`.
        pub const seedCameraFromComponent = CameraMixin.seedCameraFromComponent;
        /// MERGE a JSON patch into an entity's `Camera` component and re-seed.
        /// Backs the `editor_set_component("Camera", …)` bridge export.
        pub const applyCameraComponentJson = CameraMixin.applyCameraComponentJson;
        /// Insert a default `Camera` entity into the just-instantiated ROOT
        /// tree when it declares none (labelle-engine#564). The assembler
        /// emits a call to this at the root-instantiation site only; the
        /// engine decides *whether* a camera is needed at runtime. See
        /// `game/camera_mixin.zig` / RFC-CAMERA-PREFABS §"How this subsumes #564".
        pub const ensureDefaultCamera = CameraMixin.ensureDefaultCamera;

        // ── Atlas ─────────────────────────────────────────────────

        const has_load_texture = @hasDecl(RenderImpl, "loadTexture");

        // The atlas + streaming-asset API lives in `game/atlas_mixin.zig`;
        // see there for the full per-method docs. Capability-gated entries
        // fold to a `@compileError` shell on renderers that lack the
        // matching texture-loading hook (`loadTexture` / `loadTextureFromMemory`).
        pub const loadAtlas = if (has_load_texture) AtlasMixin.loadAtlasImpl else @compileError("Renderer does not support loadTexture");
        pub const loadAtlasComptime = if (has_load_texture) AtlasMixin.loadAtlasComptimeImpl else @compileError("Renderer does not support loadTexture");

        const has_load_from_memory = @hasDecl(RenderImpl, "loadTextureFromMemory");
        pub const loadAtlasFromMemory = if (has_load_from_memory) AtlasMixin.loadAtlasFromMemoryImpl else @compileError("Renderer does not support loadTextureFromMemory");
        pub const registerAtlasFromMemory = if (has_load_from_memory) AtlasMixin.registerAtlasFromMemoryImpl else @compileError("Renderer does not support loadTextureFromMemory");
        pub const loadAtlasIfNeeded = if (has_load_from_memory) AtlasMixin.loadAtlasIfNeededImpl else @compileError("Renderer does not support loadTextureFromMemory");

        /// Upload a standalone in-memory texture (e.g. a plugin's atlas PNG)
        /// and get back its renderer texture id as a plain `u32` — the numeric
        /// handle `drawMesh` expects. Forwards to `renderer.loadTextureFromMemory`
        /// and normalises the returned `TextureId`. Gated on the renderer
        /// exposing `loadTextureFromMemory` (render-mesh seam, labelle-gfx#290).
        pub const loadTextureFromMemory = if (has_load_from_memory) AtlasMixin.loadTextureFromMemoryU32 else @compileError("Renderer does not support loadTextureFromMemory");

        // ── Audio asset shims (Phase 4 of Asset Streaming RFC, #447) ──
        pub const registerSoundFromMemory = AtlasMixin.registerSoundFromMemory;
        pub const loadSoundFromMemory = AtlasMixin.loadSoundFromMemory;
        pub const loadSoundIfNeeded = AtlasMixin.loadSoundIfNeeded;

        // ── Font asset shims (Phase 4 of Asset Streaming RFC, #448) ──
        pub const registerFontFromMemory = AtlasMixin.registerFontFromMemory;
        pub const loadFontFromMemory = AtlasMixin.loadFontFromMemory;
        pub const loadFontIfNeeded = AtlasMixin.loadFontIfNeeded;

        pub const isAtlasLoaded = AtlasMixin.isAtlasLoaded;
        pub const getTextureManager = AtlasMixin.getTextureManager;
        pub const findSprite = AtlasMixin.findSprite;
        pub const findSpriteCached = AtlasMixin.findSpriteCached;
        pub const unloadAtlas = AtlasMixin.unloadAtlas;

        // ── Accessors ─────────────────────────────────────────────

        pub const getRenderer = MiscMixin.getRenderer;
        pub const getEcsBackend = MiscMixin.getEcsBackend;
        pub const entityCount = MiscMixin.entityCount;

        // Debug inspector: FPS + profiler overlay (#380).
        pub const fps = MiscMixin.fps;
        pub const frameTimeMs = MiscMixin.frameTimeMs;
        pub const frameStats = MiscMixin.frameStats;
        pub const scriptProfileRows = MiscMixin.scriptProfileRows;
        pub const pluginProfileRows = MiscMixin.pluginProfileRows;
        pub const frameHistory = MiscMixin.frameHistory;
        pub const setProfilingCapture = MiscMixin.setProfilingCapture;
        pub const profilingCaptureActive = MiscMixin.profilingCaptureActive;
    };
}

/// Convenience: Game with custom hooks, StubRender + mock ECS
pub fn GameWith(comptime Hooks: type) type {
    const EmptyComponents = struct {
        pub fn has(comptime _: []const u8) bool {
            return false;
        }
        pub fn names() []const []const u8 {
            return &.{};
        }
    };
    return GameConfig(
        core.StubRender(MockEcsBackend(u32).Entity),
        MockEcsBackend(u32),
        @import("input.zig").StubInput,
        @import("audio.zig").StubAudio,
        core.StubVideo,
        @import("gui.zig").StubGui,
        Hooks,
        core.StubLogSink,
        EmptyComponents,
        &.{}, // no gizmo categories
        void, // no game events
    );
}

/// Convenience: full mock game for testing
pub const Game = GameWith(void);
