// ============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT
// ============================================================================
// This file is generated by labelle-engine from project.labelle
// Any manual changes will be overwritten on next generation.
//
// To regenerate: zig build generate
// To modify settings: edit project.labelle instead
// ============================================================================

const std = @import("std");

/// Graphics backend selection (must match labelle-engine)
pub const Backend = enum {
    raylib,
    sokol,
    sdl,
    bgfx,
    wgpu_native,
};

/// ECS backend selection (must match labelle-engine)
pub const EcsBackend = enum {
    zig_ecs,
    zflecs,
};

/// GUI backend selection (must match labelle-engine)
pub const GuiBackend = enum {
    none,
    raygui,
    microui,
    nuklear,
    imgui,
};

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // Detect iOS target for framework linking
    const is_ios = target.result.os.tag == .ios;

    // Backend options - can be overridden via -Dbackend, -Decs_backend, -Dgui_backend
    const backend = b.option(Backend, "backend", "Graphics backend to use (default: raylib)") orelse .raylib;
    const ecs_backend = b.option(EcsBackend, "ecs_backend", "ECS backend to use (default: zig_ecs)") orelse .zig_ecs;
    const gui_backend = b.option(GuiBackend, "gui_backend", "GUI backend to use (default: none)") orelse .none;
    const physics_enabled = b.option(bool, "physics", "Enable physics module (default: true)") orelse true;

    const engine_dep = b.dependency("labelle-engine", .{
        .target = target,
        .optimize = optimize,
        .backend = backend,
        .ecs_backend = ecs_backend,
        .gui_backend = gui_backend,
        .physics = physics_enabled,
    });
    const engine_mod = engine_dep.module("labelle-engine");

    const exe_mod = b.createModule(.{
        .root_source_file = b.path("../main.zig"),
        .target = target,
        .optimize = optimize,
    });
    exe_mod.addImport("labelle-engine", engine_mod);
    if (physics_enabled) {
        const physics_mod = engine_dep.module("labelle-physics");
        exe_mod.addImport("labelle-physics", physics_mod);
    }

    const exe = b.addExecutable(.{
        .name = "mobile_physics_test",
        .root_module = exe_mod,
    });
    // Link iOS frameworks when targeting iOS
    if (is_ios) {
        // Add framework search path for linking - select SDK based on target ABI
        if (target.result.abi == .simulator) {
            exe.addFrameworkPath(.{ .cwd_relative = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks" });
        } else {
            exe.addFrameworkPath(.{ .cwd_relative = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks" });
        }

        exe.linkFramework("Metal");
        exe.linkFramework("MetalKit");
        exe.linkFramework("UIKit");
        exe.linkFramework("AudioToolbox");
        exe.linkFramework("AVFoundation");
        exe.linkFramework("Foundation");
        exe.linkFramework("QuartzCore");
        exe.linkSystemLibrary("objc");
    }

    b.installArtifact(exe);

    const run_cmd = b.addRunArtifact(exe);
    run_cmd.step.dependOn(b.getInstallStep());
    // Set working directory to project root (parent of output directory)
    run_cmd.setCwd(b.path(".."));

    const run_step = b.step("run", "Run the game");
    run_step.dependOn(&run_cmd.step);
}
